const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "sip": {
    contentHTML: `<h3>What is SIP?</h3><p><strong>Systematic Investment Plan (SIP)</strong> is a method of investing a fixed amount in a mutual fund scheme at regular intervals (monthly / quarterly). SIP enables disciplined investing through <strong>rupee cost averaging</strong>, where you buy more units when prices are low and fewer when prices are high.</p><h3>How SIP Works</h3><table><thead><tr><th>Month</th><th>NAV (₹)</th><th>SIP Amount (₹)</th><th>Units Purchased</th></tr></thead><tbody><tr><td>Jan</td><td>100</td><td>5,000</td><td>50.00</td></tr><tr><td>Feb</td><td>90</td><td>5,000</td><td>55.56</td></tr><tr><td>Mar</td><td>110</td><td>5,000</td><td>45.45</td></tr><tr><td><strong>Total</strong></td><td><strong>Avg: 99.01</strong></td><td><strong>15,000</strong></td><td><strong>151.01</strong></td></tr></tbody></table><h3>SIP vs. Lump Sum</h3><table><thead><tr><th>Feature</th><th>SIP</th><th>Lump Sum</th></tr></thead><tbody><tr><td>Risk</td><td>Lower (averaged out)</td><td>Higher (timing risk)</td></tr><tr><td>Minimum</td><td>₹500/month</td><td>₹1,000-₹5,000</td></tr><tr><td>Best for</td><td>Salaried investors</td><td>Those with surplus cash</td></tr></tbody></table>`,
    faq: [
      { question: "What is the minimum amount to start a SIP?", answer: "Most mutual fund houses allow SIPs starting from as low as ₹500 per month. Some AMCs offer micro-SIPs of ₹100 per month for select schemes." },
      { question: "Can I stop or pause my SIP?", answer: "Yes, you can stop, pause, or modify your SIP at any time without penalty. Some AMCs offer a 'SIP pause' feature for up to 3 months. You can also increase/decrease the SIP amount or change the date." },
      { question: "Is SIP better than Fixed Deposit?", answer: "SIPs in equity mutual funds have historically delivered 10-15% annualized returns over 10+ year periods, compared to 6-7% from FDs. However, SIP returns are not guaranteed and carry market risk, while FDs offer assured returns." }
    ]
  },
  "nav": {
    contentHTML: `<h3>What is NAV?</h3><p><strong>Net Asset Value (NAV)</strong> is the per-unit price of a mutual fund scheme. It is calculated by dividing the total value of all assets in the fund (minus liabilities) by the total number of outstanding units.</p><h3>NAV Formula</h3><p><strong>NAV = (Total Assets − Total Liabilities) ÷ Number of Outstanding Units</strong></p><h3>Common Myths About NAV</h3><table><thead><tr><th>Myth</th><th>Reality</th></tr></thead><tbody><tr><td>Low NAV = cheap/better fund</td><td>NAV has no relation to a fund being cheap or expensive. Returns depend on portfolio quality, not NAV.</td></tr><tr><td>High NAV = expensive fund</td><td>A fund with NAV ₹500 can give the same 15% return as one with NAV ₹15</td></tr><tr><td>Always buy low NAV funds</td><td>A newer fund with low NAV is not inherently better than an older fund with high NAV</td></tr></tbody></table>`,
    faq: [
      { question: "Is a mutual fund with lower NAV a better investment?", answer: "No. NAV is just the per-unit price and has nothing to do with how good or bad a fund is. What matters is the fund's return percentage. A fund with NAV ₹500 giving 12% returns is better than a fund with NAV ₹10 giving 8% returns." },
      { question: "When is NAV updated?", answer: "Mutual fund NAVs are updated at the end of each business day (after market close). SEBI mandates that AMCs publish NAVs by 11 PM on each business day. For liquid/overnight funds, same-day NAV applies for investments before the cut-off time." },
      { question: "Does NAV include the expense ratio?", answer: "Yes, the NAV already accounts for the expense ratio. The TER (Total Expense Ratio) is deducted daily from the fund's assets before calculating NAV, so whenever you see the NAV, the fund management charges are already factored in." }
    ]
  },
  "cagr": {
    contentHTML: `<h3>What is CAGR?</h3><p><strong>Compound Annual Growth Rate (CAGR)</strong> is the annualized rate of return for an investment over a specified period, assuming profits are reinvested. It smooths out the volatility of year-to-year returns and gives a single growth rate.</p><h3>CAGR Formula</h3><p><strong>CAGR = (Ending Value / Beginning Value)<sup>(1/n)</sup> − 1</strong></p><h3>Example</h3><table><thead><tr><th>Detail</th><th>Value</th></tr></thead><tbody><tr><td>Initial Investment</td><td>₹1,00,000</td></tr><tr><td>Value after 5 years</td><td>₹1,80,000</td></tr><tr><td>CAGR</td><td>(1,80,000/1,00,000)^(1/5) − 1 = <strong>12.47%</strong></td></tr></tbody></table><h3>CAGR vs. Absolute Returns</h3><table><thead><tr><th>Metric</th><th>Use Case</th><th>Limitation</th></tr></thead><tbody><tr><td><strong>CAGR</strong></td><td>Annualized comparison across different periods</td><td>Doesn't show volatility</td></tr><tr><td><strong>Absolute Return</strong></td><td>Total gain/loss</td><td>Doesn't account for time</td></tr><tr><td><strong>XIRR</strong></td><td>When multiple cash flows (SIPs)</td><td>More complex to calculate</td></tr></tbody></table>`,
    faq: [
      { question: "Can I use CAGR for SIP investments?", answer: "CAGR is not ideal for SIP investments because it assumes a single lump-sum investment. For SIPs (multiple investments at different times), XIRR (Extended Internal Rate of Return) gives a more accurate annualized return." },
      { question: "What is a good CAGR for equity investments?", answer: "For Indian equity mutual funds, a CAGR of 12-15% over 10+ years is considered good. The Nifty 50 has delivered approximately 11-13% CAGR over the past 20 years. Higher returns come with higher risk." },
      { question: "Why does CAGR differ from average annual return?", answer: "Average return is the arithmetic mean of yearly returns, which can be misleading due to volatility. CAGR accounts for compounding and gives the actual growth rate. For example, if a fund returns +50% in Year 1 and −30% in Year 2, the average return is 10%, but CAGR is only 2.47%." }
    ]
  },
  "xirr": {
    contentHTML: `<h3>What is XIRR?</h3><p><strong>XIRR (Extended Internal Rate of Return)</strong> calculates the annualized return on investments with multiple cash flows at irregular intervals — making it the most accurate return metric for SIP investments, partial withdrawals, and additional top-ups.</p><h3>When to Use XIRR vs. CAGR</h3><table><thead><tr><th>Scenario</th><th>Use XIRR</th><th>Use CAGR</th></tr></thead><tbody><tr><td>Monthly SIP</td><td>✓ Best</td><td>✗ Inaccurate</td></tr><tr><td>Lump sum investment</td><td>✓ Works</td><td>✓ Best (simpler)</td></tr><tr><td>SIP + lump sum mix</td><td>✓ Best</td><td>✗ Inaccurate</td></tr><tr><td>Multiple redemptions</td><td>✓ Best</td><td>✗ Cannot handle</td></tr></tbody></table><h3>How to Calculate XIRR</h3><p>XIRR is best calculated using <strong>Excel/Google Sheets</strong>: <code>=XIRR(cash_flows, dates)</code>. Cash outflows (investments) are entered as negative values and inflows (redemptions/current value) as positive. The final row should be the current portfolio value with today's date.</p>`,
    faq: [
      { question: "Why is XIRR more accurate for SIP returns than CAGR?", answer: "CAGR assumes a single investment at the start. But in SIP, you invest every month at different NAVs. XIRR accounts for each individual cash flow and its timing, giving you the true annualized return on your total invested capital." },
      { question: "What is a good XIRR for SIP investments?", answer: "A good XIRR for equity SIPs over 5+ years is 12-18%. For debt fund SIPs, 7-9% is reasonable. Remember that XIRR can be very high or very low for short periods due to market volatility — always evaluate over 3+ year horizons." },
      { question: "How do I calculate XIRR for my mutual fund SIP?", answer: "List all your SIP investments (as negative values) with their dates in one column, and your current portfolio value (as a positive value) with today's date as the last entry. Use the XIRR function in Excel or Google Sheets on these two columns." }
    ]
  },
  "compound-interest": {
    contentHTML: `<h3>What is Compound Interest?</h3><p><strong>Compound interest</strong> is interest calculated on both the initial principal AND the accumulated interest from previous periods. It is the basis of wealth creation and is famously called "the eighth wonder of the world" by Albert Einstein.</p><h3>Formula</h3><p><strong>A = P × (1 + r/n)<sup>nt</sup></strong></p><table><thead><tr><th>Variable</th><th>Meaning</th></tr></thead><tbody><tr><td>A</td><td>Final amount</td></tr><tr><td>P</td><td>Principal (initial investment)</td></tr><tr><td>r</td><td>Annual interest rate (decimal)</td></tr><tr><td>n</td><td>Compounding frequency per year</td></tr><tr><td>t</td><td>Number of years</td></tr></tbody></table><h3>Impact of Compounding Frequency</h3><table><thead><tr><th>Compounding</th><th>₹1,00,000 at 10% for 10 years</th></tr></thead><tbody><tr><td>Annual</td><td>₹2,59,374</td></tr><tr><td>Quarterly</td><td>₹2,68,506</td></tr><tr><td>Monthly</td><td>₹2,70,704</td></tr><tr><td>Daily</td><td>₹2,71,791</td></tr></tbody></table>`,
    faq: [
      { question: "What is the difference between simple and compound interest?", answer: "Simple interest is calculated only on the original principal (Interest = P × R × T), so it grows linearly. Compound interest is calculated on the principal plus accumulated interest, so it grows exponentially. Over long periods, compound interest generates significantly more returns." },
      { question: "How does compounding frequency affect returns?", answer: "The more frequently interest is compounded, the higher the effective return. Monthly compounding yields more than quarterly, which yields more than annual. However, the difference between monthly and daily compounding is minimal." },
      { question: "Where is compound interest used in India?", answer: "Compound interest is used in FDs (quarterly compounding), PPF (annual compounding), mutual fund returns (daily compounding), recurring deposits, and savings accounts. Loan EMIs also use compound interest via the reducing balance method." }
    ]
  },
  "simple-interest": {
    contentHTML: `<h3>What is Simple Interest?</h3><p><strong>Simple interest</strong> is interest calculated only on the original principal amount for the entire period. It does not compound — meaning interest earned is not reinvested to earn further interest. It grows linearly over time.</p><h3>Formula</h3><p><strong>SI = P × R × T / 100</strong></p><table><thead><tr><th>Variable</th><th>Meaning</th><th>Example</th></tr></thead><tbody><tr><td>P</td><td>Principal</td><td>₹1,00,000</td></tr><tr><td>R</td><td>Rate of interest (annual %)</td><td>8%</td></tr><tr><td>T</td><td>Time (years)</td><td>3 years</td></tr><tr><td><strong>SI</strong></td><td><strong>Interest earned</strong></td><td><strong>₹24,000</strong></td></tr></tbody></table><h3>Where Simple Interest Is Used</h3><ul><li>Short-term personal loans from some NBFCs</li><li>Flat rate car/bike loans (effectively simple interest)</li><li>Treasury bills and some government instruments</li><li>Basic math/academic calculations</li></ul>`,
    faq: [
      { question: "Where is simple interest actually used in real life?", answer: "Simple interest is rarely used for long-term investments or loans in India. It appears in flat-rate vehicle loans, some short-term personal loans, treasury bills, and academic calculations. Most real financial products use compound interest." },
      { question: "How much more does compound interest earn compared to simple interest?", answer: "Over short periods, the difference is small. Over long periods, it's dramatic. For example, ₹1 lakh at 10% for 20 years: Simple Interest = ₹3,00,000 (total), Compound Interest = ₹6,72,750 (total). Compound interest earns ₹3,72,750 more." },
      { question: "Is simple interest better for borrowers?", answer: "Yes, simple interest results in lower total interest paid compared to compound interest. However, most loans in India use compound interest via the reducing balance method, which is still cheaper than flat-rate (simple) interest because you pay interest only on the reducing balance." }
    ]
  },
  "fixed-deposit": {
    contentHTML: `<h3>What is a Fixed Deposit?</h3><p>A <strong>Fixed Deposit (FD)</strong> is a financial instrument where you deposit a lump sum with a bank or NBFC for a predetermined period at a fixed interest rate. FDs are one of the safest investment options in India, with bank FDs up to ₹5 lakh covered by <strong>DICGC insurance</strong>.</p><h3>FD Interest Rates (Major Banks — Indicative)</h3><table><thead><tr><th>Bank</th><th>1 Year</th><th>3 Years</th><th>5 Years</th><th>Senior Citizen Extra</th></tr></thead><tbody><tr><td>SBI</td><td>6.80%</td><td>7.00%</td><td>6.50%</td><td>+0.50%</td></tr><tr><td>HDFC</td><td>6.60%</td><td>7.10%</td><td>7.00%</td><td>+0.50%</td></tr><tr><td>Post Office</td><td>6.90%</td><td>7.10%</td><td>7.50%</td><td>—</td></tr></tbody></table><h3>Tax on FD Interest</h3><ul><li>FD interest is <strong>fully taxable</strong> as per your income tax slab</li><li><strong>TDS</strong> of 10% deducted if annual interest exceeds ₹40,000 (₹50,000 for senior citizens)</li><li><strong>Tax-saving FDs</strong> (5-year lock-in) qualify for Section 80C deduction up to ₹1.5 lakh</li></ul>`,
    faq: [
      { question: "Is FD interest taxable?", answer: "Yes, FD interest is fully taxable as per your income tax slab. Banks deduct TDS at 10% if annual interest exceeds ₹40,000 (₹50,000 for senior citizens). If your total income is below the taxable limit, you can submit Form 15G/15H to avoid TDS." },
      { question: "Can I break an FD before maturity?", answer: "Yes, most banks allow premature withdrawal, but they charge a penalty of 0.5-1% on the applicable interest rate. Some banks have 'no-penalty' FDs with slightly lower rates. Alternatively, you can take a loan against FD (up to 90% of FD value) without breaking it." },
      { question: "Is FD safe if the bank fails?", answer: "Bank FDs are insured by DICGC (Deposit Insurance and Credit Guarantee Corporation) for up to ₹5 lakh per depositor per bank. For amounts above ₹5 lakh, there is some risk, especially with small/cooperative banks." }
    ]
  },
  "recurring-deposit": {
    contentHTML: `<h3>What is a Recurring Deposit?</h3><p>A <strong>Recurring Deposit (RD)</strong> is a savings instrument where you deposit a fixed amount every month for a predetermined period and earn compound interest. It is like an SIP version of a Fixed Deposit — ideal for salaried individuals who want guaranteed, disciplined savings.</p><h3>RD vs. FD vs. SIP</h3><table><thead><tr><th>Feature</th><th>RD</th><th>FD</th><th>SIP (Mutual Fund)</th></tr></thead><tbody><tr><td>Investment type</td><td>Monthly fixed</td><td>Lump sum</td><td>Monthly flexible</td></tr><tr><td>Returns</td><td>Fixed (6-7%)</td><td>Fixed (6-7.5%)</td><td>Market-linked (10-15%)</td></tr><tr><td>Risk</td><td>Nearly zero</td><td>Nearly zero</td><td>Moderate to high</td></tr><tr><td>Tax</td><td>Fully taxable</td><td>Fully taxable</td><td>LTCG rules apply</td></tr></tbody></table><h3>RD Maturity Calculation</h3><p><strong>Interest is compounded quarterly.</strong> For a ₹5,000/month RD at 7% for 3 years, the maturity value is approximately ₹2,02,230 (total deposit: ₹1,80,000 + interest: ₹22,230).</p>`,
    faq: [
      { question: "Is RD better than SIP?", answer: "RD offers guaranteed but lower returns (6-7%), while SIP offers potentially higher returns (10-15%) with market risk. For risk-averse investors or short-term goals (1-3 years), RD is safer. For long-term wealth creation (5+ years), SIP in equity funds is historically better." },
      { question: "What happens if I miss an RD installment?", answer: "If you miss an installment, the bank charges a penalty (typically ₹1-2 per ₹100 per month of default). If installments are missed for 3-6 consecutive months, the RD may be prematurely closed with a penalty on the interest rate." },
      { question: "Is RD interest taxable?", answer: "Yes, RD interest is fully taxable as per your income tax slab. TDS is deducted at 10% if the annual interest across all RDs and FDs at the bank exceeds ₹40,000 (₹50,000 for senior citizens)." }
    ]
  },
  "nps": {
    contentHTML: `<h3>What is NPS?</h3><p><strong>National Pension System (NPS)</strong> is a government-sponsored retirement savings scheme regulated by PFRDA. It offers market-linked returns through a mix of equity, corporate debt, and government bonds, with significant tax benefits.</p><h3>NPS Tax Benefits</h3><table><thead><tr><th>Section</th><th>Deduction</th><th>Regime</th></tr></thead><tbody><tr><td><strong>80CCD(1)</strong></td><td>Up to ₹1.5L (within 80C limit)</td><td>Old regime</td></tr><tr><td><strong>80CCD(1B)</strong></td><td>Additional ₹50,000 (over and above 80C)</td><td>Both old & new</td></tr><tr><td><strong>80CCD(2)</strong></td><td>Employer contribution (up to 10% of salary)</td><td>Both old & new</td></tr></tbody></table><h3>NPS Account Types</h3><table><thead><tr><th>Account</th><th>Purpose</th><th>Withdrawal</th></tr></thead><tbody><tr><td><strong>Tier I</strong></td><td>Retirement savings (mandatory)</td><td>Locked until 60 (partial withdrawal allowed)</td></tr><tr><td><strong>Tier II</strong></td><td>Voluntary savings (like mutual fund)</td><td>Anytime, no tax benefit</td></tr></tbody></table>`,
    faq: [
      { question: "Can I withdraw from NPS before age 60?", answer: "Partial withdrawal is allowed from Tier I after 3 years of account opening, for specified purposes (children's education, marriage, home purchase, medical emergencies) — up to 25% of your own contributions. Full premature exit before 60 requires 80% annuity purchase." },
      { question: "What is the extra ₹50,000 tax benefit under NPS?", answer: "Section 80CCD(1B) provides an additional ₹50,000 deduction for NPS contributions, over and above the ₹1.5 lakh limit of Section 80C. This is available under both old and new tax regimes, making NPS one of the most tax-efficient investments." },
      { question: "How much pension will I get from NPS?", answer: "Your pension depends on total corpus accumulated and the annuity rate at retirement. At age 60, you must use at least 40% of the corpus to buy an annuity (pension). The remaining 60% can be withdrawn tax-free. If your corpus is below ₹5 lakh, you can withdraw 100%." }
    ]
  },
  "elss": {
    contentHTML: `<h3>What is ELSS?</h3><p><strong>Equity Linked Savings Scheme (ELSS)</strong> is a type of equity mutual fund that offers tax deduction under <strong>Section 80C</strong> (up to ₹1.5 lakh). It has the shortest lock-in period (3 years) among all 80C instruments.</p><h3>ELSS vs. Other 80C Investments</h3><table><thead><tr><th>Investment</th><th>Lock-in</th><th>Returns</th><th>Risk</th></tr></thead><tbody><tr><td><strong>ELSS</strong></td><td>3 years</td><td>10-15% (market-linked)</td><td>Moderate-High</td></tr><tr><td>PPF</td><td>15 years</td><td>7.1% (fixed)</td><td>Zero</td></tr><tr><td>Tax-Saving FD</td><td>5 years</td><td>6.5-7%</td><td>Very Low</td></tr><tr><td>NSC</td><td>5 years</td><td>7.7% (fixed)</td><td>Zero</td></tr></tbody></table><h3>ELSS Tax Treatment</h3><ul><li><strong>Investment:</strong> Deductible under Sec 80C (up to ₹1.5L)</li><li><strong>Gains up to ₹1.25L:</strong> Tax-free (LTCG)</li><li><strong>Gains above ₹1.25L:</strong> Taxed at 12.5% (LTCG)</li></ul>`,
    faq: [
      { question: "Is ELSS the best tax-saving investment?", answer: "ELSS offers the best combination of shortest lock-in (3 years), highest potential returns (10-15% historically), and Section 80C deduction. However, it carries market risk. For zero-risk investors, PPF is safer but has a 15-year lock-in." },
      { question: "Can I invest in ELSS through SIP?", answer: "Yes, SIP in ELSS is very popular. Each monthly SIP instalment has its own 3-year lock-in. For example, a January 2024 SIP is locked until January 2027, February 2024 SIP until February 2027, and so on." },
      { question: "What happens after the 3-year lock-in period in ELSS?", answer: "After 3 years, your ELSS units are automatically unlocked and can be redeemed at any time. However, you can continue to hold them for longer if the fund is performing well — there is no compulsion to sell." }
    ]
  },
  "mutual-fund": {
    contentHTML: `<h3>What is a Mutual Fund?</h3><p>A <strong>mutual fund</strong> is a pooled investment vehicle managed by a professional fund manager (AMC). It collects money from multiple investors and invests in diversified assets — equities, bonds, money market instruments, or a combination.</p><h3>Types of Mutual Funds in India</h3><table><thead><tr><th>Category</th><th>Risk</th><th>Expected Returns</th><th>Ideal For</th></tr></thead><tbody><tr><td><strong>Large Cap</strong></td><td>Moderate</td><td>10-12%</td><td>Stability + growth</td></tr><tr><td><strong>Mid Cap</strong></td><td>High</td><td>12-15%</td><td>Growth investors</td></tr><tr><td><strong>Small Cap</strong></td><td>Very High</td><td>15-20%</td><td>Aggressive investors</td></tr><tr><td><strong>Flexi Cap</strong></td><td>Moderate-High</td><td>11-14%</td><td>Diversified exposure</td></tr><tr><td><strong>Debt Funds</strong></td><td>Low</td><td>6-8%</td><td>Capital preservation</td></tr><tr><td><strong>Index Funds</strong></td><td>Moderate</td><td>10-12%</td><td>Passive investors</td></tr></tbody></table>`,
    faq: [
      { question: "How do I start investing in mutual funds in India?", answer: "You need: (1) PAN card, (2) Aadhaar for e-KYC, (3) bank account. Complete KYC online via any AMC website or aggregator app (Groww, Zerodha, Kuvera). You can start with just ₹500/month via SIP." },
      { question: "Are mutual fund returns guaranteed?", answer: "No. Mutual fund investments are subject to market risk. Returns depend on the performance of the underlying securities. Historical returns are not indicative of future performance. However, equity mutual funds have historically outperformed FDs over 7+ year periods." },
      { question: "What is the difference between direct and regular mutual fund plans?", answer: "Direct plans are purchased directly from the AMC without a distributor, resulting in a lower expense ratio (0.5-1% less). Regular plans are bought through distributors who receive a commission, increasing the expense ratio. Over long periods, direct plans can generate 1-2% higher annualized returns." }
    ]
  },
  "index-fund": {
    contentHTML: `<h3>What is an Index Fund?</h3><p>An <strong>index fund</strong> is a passively managed mutual fund that replicates the composition and performance of a market index (like Nifty 50 or Sensex). Instead of trying to beat the market, it aims to <strong>match</strong> the index's returns at a very low cost.</p><h3>Popular Index Funds in India</h3><table><thead><tr><th>Index Tracked</th><th>Type</th><th>Typical Expense Ratio</th></tr></thead><tbody><tr><td><strong>Nifty 50</strong></td><td>Top 50 large-cap stocks</td><td>0.10-0.20%</td></tr><tr><td><strong>Sensex 30</strong></td><td>Top 30 BSE stocks</td><td>0.10-0.20%</td></tr><tr><td><strong>Nifty Next 50</strong></td><td>Stocks ranked 51-100</td><td>0.15-0.30%</td></tr><tr><td><strong>Nifty Midcap 150</strong></td><td>Mid-cap stocks</td><td>0.20-0.40%</td></tr></tbody></table><h3>Index Fund vs. Active Fund</h3><table><thead><tr><th>Feature</th><th>Index Fund</th><th>Active Fund</th></tr></thead><tbody><tr><td>Management</td><td>Passive (follows index)</td><td>Active (fund manager picks stocks)</td></tr><tr><td>Expense ratio</td><td>0.10-0.30%</td><td>0.80-2.50%</td></tr><tr><td>Returns</td><td>Match market</td><td>May beat/lag market</td></tr></tbody></table>`,
    faq: [
      { question: "Is an index fund better than an actively managed fund?", answer: "Over long periods (10+ years), most actively managed funds fail to consistently beat their benchmark index after fees. Index funds guarantee market returns at a fraction of the cost. However, in India's less-efficient mid/small-cap segments, active funds still have room to outperform." },
      { question: "What is the expense ratio for index funds in India?", answer: "Index fund expense ratios in India range from 0.05% to 0.40%, compared to 0.80-2.50% for actively managed funds. The lower cost directly translates to higher net returns for investors over time." },
      { question: "Can I start a SIP in an index fund?", answer: "Yes, all major AMCs offer SIP options for their index funds with minimums as low as ₹500/month. Index fund SIPs are increasingly popular for long-term wealth building due to simplicity and low cost." }
    ]
  },
  "expense-ratio": {
    contentHTML: `<h3>What is Expense Ratio?</h3><p><strong>Expense ratio (TER — Total Expense Ratio)</strong> is the annual fee charged by a mutual fund to manage your investment. It includes fund management fees, administrative costs, marketing expenses, and other operational costs. The expense ratio is deducted daily from the fund's NAV.</p><h3>SEBI Expense Ratio Limits (Equity Funds)</h3><table><thead><tr><th>AUM Slab</th><th>Maximum TER (Regular)</th></tr></thead><tbody><tr><td>First ₹500 crore</td><td>2.25%</td></tr><tr><td>Next ₹250 crore</td><td>2.00%</td></tr><tr><td>Next ₹1,250 crore</td><td>1.75%</td></tr><tr><td>Above ₹50,000 crore</td><td>1.05%</td></tr></tbody></table><h3>Impact of Expense Ratio on Returns</h3><p>If two funds deliver 12% gross return, one with 0.5% TER gives you 11.5% net, while one with 2% TER gives 10% net. Over 20 years on ₹10,000/month SIP, that 1.5% difference means ₹<strong>15-20 lakh</strong> less in your corpus.</p>`,
    faq: [
      { question: "How does the expense ratio affect my mutual fund returns?", answer: "The expense ratio is deducted from the fund's returns before you see them reflected in the NAV. A 1% expense ratio on a fund earning 12% gross means you receive 11% net returns. Over long periods, even a 0.5% difference in expense ratio can compound into lakhs of rupees." },
      { question: "Is a lower expense ratio always better?", answer: "Not always. A slightly higher expense ratio is justified if the fund consistently outperforms its benchmark by more than the extra cost. However, for index funds and debt funds, lower expense ratio is almost always better since there is minimal fund manager value-add." },
      { question: "What is the difference between direct and regular plan expense ratios?", answer: "Direct plans have a lower expense ratio (typically 0.5-1% less) than regular plans because no distributor commission is included. Over a 20-year SIP, this difference can translate to 20-30% more wealth in the direct plan." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' invest terms (batch 1)');
