const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "bmi-term": {
    contentHTML: `<h3>What is BMI?</h3><p><strong>Body Mass Index (BMI)</strong> is a numerical value calculated from a person's weight and height, used as a screening tool to categorize weight status. While not a direct measure of body fat, BMI provides a quick and inexpensive method to assess whether someone is underweight, normal weight, overweight, or obese.</p><h3>BMI Formula</h3><p><strong>BMI = Weight (kg) ÷ Height² (m²)</strong></p><h3>BMI Categories</h3><table><thead><tr><th>BMI Range</th><th>Category</th><th>Health Risk</th></tr></thead><tbody><tr><td>Below 18.5</td><td>Underweight</td><td>Increased (malnutrition, weak immunity)</td></tr><tr><td>18.5 – 24.9</td><td>Normal</td><td>Low</td></tr><tr><td>25.0 – 29.9</td><td>Overweight</td><td>Increased (heart disease, diabetes)</td></tr><tr><td>30.0 – 34.9</td><td>Obese Class I</td><td>High</td></tr><tr><td>35.0 – 39.9</td><td>Obese Class II</td><td>Very High</td></tr><tr><td>Above 40</td><td>Obese Class III</td><td>Extremely High</td></tr></tbody></table><h3>Limitations of BMI</h3><ul><li>Does not distinguish between muscle and fat (athletes may have high BMI but low body fat)</li><li>Does not account for body composition, age, gender, or ethnicity</li><li>Asian populations may have higher health risks at lower BMI thresholds</li></ul>`,
    faq: [
      { question: "What is a healthy BMI range?", answer: "A BMI between 18.5 and 24.9 is considered normal/healthy for adults. However, for Asian populations, the World Health Organization suggests that health risks may increase at a BMI of 23 or above, recommending a lower threshold." },
      { question: "Is BMI accurate for athletes and muscular people?", answer: "No, BMI can be misleading for muscular individuals because muscle weighs more than fat. A bodybuilder might have a BMI of 30+ (classified as 'obese') despite having very low body fat. For athletes, body fat percentage is a better metric." },
      { question: "How is BMI different from body fat percentage?", answer: "BMI is a simple weight-to-height ratio and does not directly measure fat. Body fat percentage measures the actual proportion of fat tissue in your body. BMI is a screening tool; body fat percentage (measured via DEXA scan or calipers) is more precise." }
    ]
  },
  "percentage-term": {
    contentHTML: `<h3>What is a Percentage?</h3><p>A <strong>percentage</strong> is a number expressed as a fraction of 100, denoted by the symbol <strong>%</strong>. It is one of the most commonly used mathematical concepts in everyday life — from calculating discounts and tips to understanding interest rates and exam scores.</p><h3>Key Percentage Formulas</h3><table><thead><tr><th>Calculation</th><th>Formula</th><th>Example</th></tr></thead><tbody><tr><td>Percentage of a number</td><td>(Part / Whole) × 100</td><td>45 out of 60 = (45/60) × 100 = 75%</td></tr><tr><td>Percentage increase</td><td>((New - Old) / Old) × 100</td><td>Price ₹100 → ₹120 = 20% increase</td></tr><tr><td>Percentage decrease</td><td>((Old - New) / Old) × 100</td><td>Price ₹100 → ₹80 = 20% decrease</td></tr><tr><td>Discount amount</td><td>Original Price × (Discount% / 100)</td><td>₹500 × 30% = ₹150 off</td></tr></tbody></table><h3>Common Usage</h3><ul><li><strong>Finance:</strong> Interest rates, returns, tax rates</li><li><strong>Shopping:</strong> Discounts, GST calculations</li><li><strong>Education:</strong> Exam scores, grading</li><li><strong>Health:</strong> BMI, body fat %, daily nutrient values</li></ul>`,
    faq: [
      { question: "How do I calculate percentage increase or decrease?", answer: "Percentage Change = ((New Value − Old Value) / Old Value) × 100. If the result is positive, it's an increase; if negative, it's a decrease. Example: Salary changes from ₹50,000 to ₹55,000 → ((55,000 − 50,000) / 50,000) × 100 = 10% increase." },
      { question: "How do I find what percentage one number is of another?", answer: "Divide the part by the whole and multiply by 100. Example: 150 is what % of 600? → (150/600) × 100 = 25%." },
      { question: "Is a 50% decrease followed by a 50% increase the same as the original?", answer: "No. If ₹100 decreases by 50%, it becomes ₹50. A 50% increase on ₹50 gives only ₹75 (not ₹100). This is because percentages are relative to the current value, not the original." }
    ]
  },
  "rule-of-72": {
    contentHTML: `<h3>What is the Rule of 72?</h3><p>The <strong>Rule of 72</strong> is a quick mental math formula to estimate how many years it takes for an investment to double at a given annual rate of return: <strong>Years to Double ≈ 72 ÷ Rate of Return</strong>.</p><h3>Examples</h3><table><thead><tr><th>Annual Return</th><th>Years to Double</th><th>Common Investment</th></tr></thead><tbody><tr><td>4%</td><td>18 years</td><td>Savings account</td></tr><tr><td>6%</td><td>12 years</td><td>FD / Debt funds</td></tr><tr><td>8%</td><td>9 years</td><td>PPF / Conservative hybrid</td></tr><tr><td>10%</td><td>7.2 years</td><td>Balanced mutual funds</td></tr><tr><td>12%</td><td>6 years</td><td>Equity mutual funds</td></tr><tr><td>15%</td><td>4.8 years</td><td>Aggressive equity</td></tr></tbody></table><h3>Works in Reverse Too</h3><p>Inflation also doubles using Rule of 72. At 6% inflation, prices double every 12 years. So your ₹1 crore retirement corpus will only buy ₹50 lakh worth of goods in 12 years.</p>`,
    faq: [
      { question: "How accurate is the Rule of 72?", answer: "The Rule of 72 is a good approximation for rates between 5-15%. At 10%, it predicts doubling in 7.2 years; the actual time is 7.27 years. For very high or very low rates, the accuracy decreases slightly." },
      { question: "Can I use the Rule of 72 for any compounding frequency?", answer: "The rule works best for annual compounding. For monthly or daily compounding, the Rule of 69.3 is slightly more accurate. However, for practical mental math, 72 is preferred because it has more factors (divisible by 2, 3, 4, 6, 8, 9, 12)." },
      { question: "How do I use the Rule of 72 to understand inflation's impact?", answer: "Divide 72 by the inflation rate. At 7% inflation, prices double every ~10 years. This means if you retire in 20 years, you'll need roughly 4x your current annual expenses to maintain the same lifestyle." }
    ]
  },
  "inflation": {
    contentHTML: `<h3>What is Inflation?</h3><p><strong>Inflation</strong> is the rate at which the general level of prices for goods and services rises, causing purchasing power to decrease. If inflation is 6%, something that costs ₹100 today will cost about ₹106 next year.</p><h3>Inflation in India</h3><table><thead><tr><th>Metric</th><th>Description</th><th>Target</th></tr></thead><tbody><tr><td><strong>CPI (Consumer Price Index)</strong></td><td>Official inflation measure based on consumer goods basket</td><td>RBI targets 4% (±2%)</td></tr><tr><td><strong>WPI (Wholesale Price Index)</strong></td><td>Measures price changes at wholesale level</td><td>No formal target</td></tr><tr><td><strong>Core Inflation</strong></td><td>CPI excluding food and fuel (less volatile)</td><td>—</td></tr></tbody></table><h3>Impact of Inflation on Investments</h3><table><thead><tr><th>If Inflation = 6%</th><th>Investment Return Needed</th><th>To Earn Real Return Of</th></tr></thead><tbody><tr><td>Just to break even</td><td>6%</td><td>0%</td></tr><tr><td>Modest growth</td><td>9%</td><td>3%</td></tr><tr><td>Wealth creation</td><td>12%+</td><td>6%+</td></tr></tbody></table>`,
    faq: [
      { question: "How does inflation affect my savings?", answer: "Inflation erodes the purchasing power of money. If inflation is 6% and your savings account earns 3.5%, you're losing about 2.5% of purchasing power each year. ₹10 lakh today will buy only ₹5.58 lakh worth of goods in 10 years at 6% inflation." },
      { question: "What causes inflation in India?", answer: "Key causes include: (1) Demand-pull: increased spending, (2) Cost-push: rising raw material/fuel prices, (3) Imported inflation: weak rupee increases import costs, (4) Food inflation: crop failure/monsoon disruption, (5) Monetary policy: excess money supply." },
      { question: "How does RBI control inflation?", answer: "RBI's primary tool is the repo rate. By raising the repo rate, RBI makes borrowing more expensive, which reduces spending and slows price increases. Conversely, cutting the repo rate stimulates spending. RBI targets 4% inflation (with ±2% flexibility)." }
    ]
  },
  "waist-to-hip-ratio": {
    contentHTML: `<h3>What is Waist-to-Hip Ratio?</h3><p><strong>Waist-to-Hip Ratio (WHR)</strong> is a measurement comparing the circumference of your waist to that of your hips. It is used to assess body fat distribution and associated health risks. Unlike BMI, WHR specifically indicates where fat is stored — abdominal fat (android/apple shape) carries higher health risks than hip fat (gynoid/pear shape).</p><h3>How to Measure</h3><ul><li><strong>Waist:</strong> Measure at the narrowest point between ribs and hip bones (typically at navel level)</li><li><strong>Hips:</strong> Measure at the widest point of the buttocks</li><li><strong>WHR = Waist ÷ Hips</strong></li></ul><h3>WHR Health Risk Categories</h3><table><thead><tr><th>Health Risk</th><th>Men</th><th>Women</th></tr></thead><tbody><tr><td><strong>Low</strong></td><td>Below 0.90</td><td>Below 0.80</td></tr><tr><td><strong>Moderate</strong></td><td>0.90 – 0.99</td><td>0.80 – 0.85</td></tr><tr><td><strong>High</strong></td><td>1.00 or above</td><td>0.86 or above</td></tr></tbody></table>`,
    faq: [
      { question: "Is waist-to-hip ratio better than BMI?", answer: "WHR is often considered a better predictor of cardiovascular risk because it specifically measures abdominal fat distribution, which is more strongly linked to heart disease, diabetes, and stroke. BMI doesn't tell you where fat is stored. Doctors recommend using both metrics together." },
      { question: "What is a healthy waist-to-hip ratio?", answer: "For men: below 0.90 is low risk, 0.90-0.99 is moderate, above 1.0 is high risk. For women: below 0.80 is low risk, 0.80-0.85 is moderate, above 0.86 is high risk. The World Health Organization uses these thresholds." },
      { question: "How can I improve my waist-to-hip ratio?", answer: "Focus on losing abdominal fat through: (1) aerobic exercise (30+ minutes most days), (2) reducing refined carbs and sugar, (3) strength training, (4) managing stress (cortisol promotes belly fat), (5) adequate sleep (7-9 hours)." }
    ]
  },
  "discount-rate": {
    contentHTML: `<h3>What is the Discount Rate?</h3><p>A <strong>discount rate</strong> is the interest rate used to determine the present value of future cash flows. It reflects the time value of money — the concept that a dollar today is worth more than a dollar in the future. Discount rates are central to DCF (Discounted Cash Flow) analysis, NPV calculations, and business valuation.</p><h3>Common Discount Rates</h3><table><thead><tr><th>Context</th><th>Typical Rate</th><th>Used For</th></tr></thead><tbody><tr><td><strong>Risk-Free Rate</strong></td><td>6-7% (India 10-year G-Sec)</td><td>Government bond analysis</td></tr><tr><td><strong>WACC</strong></td><td>10-15%</td><td>Corporate project evaluation</td></tr><tr><td><strong>Required Return</strong></td><td>12-20%</td><td>Equity valuation, venture capital</td></tr><tr><td><strong>Inflation Rate</strong></td><td>5-6%</td><td>Real value calculations</td></tr></tbody></table><h3>Example — Present Value</h3><p>₹1,00,000 received 3 years from now at a 10% discount rate:</p><p><strong>PV = ₹1,00,000 ÷ (1.10)³ = ₹75,131</strong></p><p>This means you would need to invest ₹75,131 today at 10% to have ₹1,00,000 in 3 years.</p>`,
    faq: [
      { question: "How do I choose the right discount rate?", answer: "The discount rate should reflect the riskiness of the cash flows. For government bonds, use the risk-free rate. For corporate projects, use WACC. For startups, use a higher rate (20-40%) to account for uncertainty. When unsure, use the opportunity cost of capital." },
      { question: "What happens when you increase the discount rate?", answer: "A higher discount rate reduces the present value of future cash flows. This means: (1) future earnings are worth less today, (2) longer-duration projects become less attractive, (3) NPV decreases. Central banks effectively raise the 'discount rate' for the economy by increasing interest rates." },
      { question: "Is discount rate the same as interest rate?", answer: "They are related but not identical. Interest rate is the cost of borrowing or the return on lending. Discount rate is the rate used to find the present value of future cash flows. In many practical scenarios, the interest rate IS used as the discount rate, but sophisticated analyses use WACC or risk-adjusted rates." }
    ]
  },
  "markup": {
    contentHTML: `<h3>What is Markup?</h3><p><strong>Markup</strong> is the amount added to the cost price of a product to determine its selling price. It is expressed as a percentage of the cost price and represents the seller's gross profit per item.</p><h3>Markup Formula</h3><p><strong>Markup % = ((Selling Price − Cost Price) / Cost Price) × 100</strong></p><h3>Markup vs. Margin</h3><table><thead><tr><th>Concept</th><th>Formula</th><th>Based On</th><th>Example (Cost ₹100, Sell ₹150)</th></tr></thead><tbody><tr><td><strong>Markup</strong></td><td>(Profit / Cost) × 100</td><td>Cost Price</td><td>(50/100) × 100 = <strong>50%</strong></td></tr><tr><td><strong>Margin</strong></td><td>(Profit / Selling Price) × 100</td><td>Selling Price</td><td>(50/150) × 100 = <strong>33.3%</strong></td></tr></tbody></table><h3>Common Industry Markups</h3><table><thead><tr><th>Industry</th><th>Typical Markup</th></tr></thead><tbody><tr><td>Retail clothing</td><td>50-100%</td></tr><tr><td>Grocery</td><td>5-25%</td></tr><tr><td>Restaurant food</td><td>200-400%</td></tr><tr><td>Jewelry</td><td>100-300%</td></tr><tr><td>Electronics</td><td>10-30%</td></tr></tbody></table>`,
    faq: [
      { question: "What is the difference between markup and profit margin?", answer: "Markup is calculated as a percentage of COST price, while margin is a percentage of SELLING price. A 50% markup equals approximately 33.3% margin. Markup is always a higher percentage than margin for the same transaction. They are two different ways of expressing the same profit." },
      { question: "How do I convert markup to margin?", answer: "Margin = Markup ÷ (1 + Markup). For example, 50% markup → 0.50/(1+0.50) = 33.3% margin. Conversely, Markup = Margin ÷ (1 − Margin). 33.3% margin → 0.333/(1−0.333) = 50% markup." },
      { question: "What markup should I use for my business?", answer: "It depends on your industry, competition, and operating costs. A general rule: your markup must cover all operating expenses (rent, salaries, utilities) plus desired profit. Research industry benchmarks and price-test with customers. Online businesses can often charge lower markups due to lower overhead." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' utility terms');
