const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "floating-rate": {
    contentHTML: `<h3>What is a Floating Interest Rate?</h3><p>A <strong>floating rate</strong> (variable rate) is an interest rate that changes periodically based on a benchmark rate set by the RBI or the bank's internal cost of funds. For most home loans in India, this benchmark is the <strong>repo rate</strong> (via EBLR). When the benchmark changes, your loan rate adjusts accordingly.</p><h3>How Floating Rates Are Determined</h3><p><strong>Your Rate = Benchmark Rate + Spread (Bank's Margin)</strong></p><table><thead><tr><th>Benchmark</th><th>Who Sets It</th><th>Transmission Speed</th></tr></thead><tbody><tr><td>Repo Rate (EBLR)</td><td>RBI</td><td>Immediate (within 3 months)</td></tr><tr><td>MCLR</td><td>Individual bank</td><td>Slow (on reset date)</td></tr></tbody></table><h3>Pros and Cons</h3><table><thead><tr><th>Pros</th><th>Cons</th></tr></thead><tbody><tr><td>Generally starts lower than fixed rate</td><td>EMI can increase when rates rise</td></tr><tr><td>Benefits from rate cuts by RBI</td><td>Budgeting uncertainty</td></tr><tr><td>No prepayment charges (RBI rule)</td><td>Rate risk over long tenures</td></tr></tbody></table>`,
    faq: [
      { question: "Is a floating rate better than a fixed rate for home loans?", answer: "For long-tenure loans (15-30 years), floating rates are generally better because they tend to be lower on average over time and benefit from RBI rate cuts. Fixed rates offer predictability but are typically 1-2% higher and may include prepayment penalties." },
      { question: "How often does a floating rate change?", answer: "For EBLR-linked loans, the rate resets every 3 months (quarterly). For MCLR-linked loans, the reset period can be 6 months or 1 year. The exact reset frequency depends on your loan agreement." },
      { question: "Can I switch from floating to fixed rate?", answer: "Yes, most banks allow conversion from floating to fixed rate and vice versa, usually for a fee of 0.5-1% of the outstanding loan amount. However, switching to a fixed rate locks you into a higher rate and may attract prepayment charges." }
    ]
  },
  "fixed-rate": {
    contentHTML: `<h3>What is a Fixed Interest Rate?</h3><p>A <strong>fixed rate</strong> is an interest rate that remains constant throughout the loan tenure, providing predictable EMIs. Fixed rate loans are less common in India for long-tenure products like home loans but are standard for short-tenure personal loans and some vehicle loans.</p><h3>Fixed Rate Availability in India</h3><table><thead><tr><th>Loan Type</th><th>Fixed Rate Availability</th><th>Typical Tenure</th></tr></thead><tbody><tr><td>Home Loan</td><td>Rare (some offer 2-5 year fixed periods)</td><td>15-30 years</td></tr><tr><td>Personal Loan</td><td>Standard</td><td>1-5 years</td></tr><tr><td>Car Loan</td><td>Common</td><td>3-7 years</td></tr><tr><td>Education Loan</td><td>Rare</td><td>5-15 years</td></tr></tbody></table><h3>When to Choose Fixed Rate</h3><ul><li>When interest rates are at historic lows and expected to rise</li><li>For short-tenure loans (1-5 years) where rate risk is limited</li><li>When you prioritize EMI predictability over potential savings</li></ul>`,
    faq: [
      { question: "Why are fixed rates higher than floating rates?", answer: "Banks charge a premium (usually 1-2%) on fixed rates to compensate for the risk they take by locking in a rate. If market rates rise significantly, the bank cannot increase your rate, so they protect themselves with a higher starting rate." },
      { question: "Is a fixed rate truly fixed for the entire tenure in India?", answer: "Many Indian banks offer 'fixed rate' home loans that are only fixed for 2-5 years, after which they convert to floating rates. True fixed rate home loans for the entire tenure (20-30 years) are rare in India. Always read the fine print." },
      { question: "Can I foreclose a fixed rate loan without penalty?", answer: "Unlike floating rate loans (where RBI mandates no prepayment penalty for individuals), fixed rate loans can carry foreclosure charges of 2-4% of the outstanding principal. Check your loan agreement for specific terms." }
    ]
  },
  "stamp-duty": {
    contentHTML: `<h3>What is Stamp Duty?</h3><p><strong>Stamp duty</strong> is a tax levied by the state government on the transfer of property ownership. It is mandatory for all property transactions (purchase, gift, lease) and must be paid at the time of property registration. Rates vary significantly by state.</p><h3>Stamp Duty Rates Across Major States</h3><table><thead><tr><th>State</th><th>Male Buyer</th><th>Female Buyer</th><th>Joint (M+F)</th></tr></thead><tbody><tr><td><strong>Maharashtra</strong></td><td>6%</td><td>6%</td><td>6%</td></tr><tr><td><strong>Delhi</strong></td><td>6%</td><td>4%</td><td>5%</td></tr><tr><td><strong>Karnataka</strong></td><td>5%</td><td>5%</td><td>5%</td></tr><tr><td><strong>Tamil Nadu</strong></td><td>7%</td><td>7%</td><td>7%</td></tr><tr><td><strong>Rajasthan</strong></td><td>6%</td><td>5%</td><td>5.5%</td></tr><tr><td><strong>UP</strong></td><td>7%</td><td>6%</td><td>6.5%</td></tr></tbody></table><h3>Tax Benefits</h3><p>Stamp duty paid on a home purchase can be claimed as a deduction under <strong>Section 80C</strong> (up to ₹1.5 lakh) in the year of payment, under the old tax regime.</p>`,
    faq: [
      { question: "Who pays stamp duty — buyer or seller?", answer: "Stamp duty is paid by the buyer (purchaser) of the property. It must be paid before or at the time of property registration at the sub-registrar's office." },
      { question: "Is stamp duty different for men and women?", answer: "In some states like Delhi and Rajasthan, women buyers get a concession on stamp duty (1-2% lower). This is why many families register property in a woman's name to save on stamp duty costs." },
      { question: "Can stamp duty be included in a home loan?", answer: "Most banks do not include stamp duty and registration charges in the home loan amount. These must be paid from your own funds, typically adding 7-10% to the property cost. Some banks offer a 'stamp duty loan' as a separate top-up." }
    ]
  },
  "eblr": {
    contentHTML: `<h3>What is EBLR?</h3><p><strong>External Benchmark Lending Rate (EBLR)</strong> is a lending rate system mandated by RBI since October 2019, where bank loan rates are linked to an external benchmark — typically the <strong>RBI Repo Rate</strong>. This ensures faster and more transparent transmission of rate changes to borrowers.</p><h3>How EBLR Works</h3><p><strong>Your Interest Rate = Repo Rate + Bank's Spread + Risk Premium</strong></p><table><thead><tr><th>Component</th><th>Example</th><th>Who Decides</th></tr></thead><tbody><tr><td>Repo Rate</td><td>6.50%</td><td>RBI</td></tr><tr><td>Bank Spread</td><td>+2.25%</td><td>Bank (fixed at sanction)</td></tr><tr><td>Risk Premium</td><td>+0.10%</td><td>Bank (based on credit profile)</td></tr><tr><td><strong>Final Rate</strong></td><td><strong>8.85%</strong></td><td>—</td></tr></tbody></table><h3>EBLR vs. MCLR</h3><table><thead><tr><th>Feature</th><th>EBLR</th><th>MCLR</th></tr></thead><tbody><tr><td>Benchmark</td><td>RBI Repo Rate</td><td>Bank's internal cost</td></tr><tr><td>Transparency</td><td>High — publicly known</td><td>Low — bank-specific</td></tr><tr><td>Reset frequency</td><td>Quarterly (mandatory)</td><td>6 months / 1 year</td></tr><tr><td>Rate transmission</td><td>Fast and automatic</td><td>Slow and discretionary</td></tr></tbody></table>`,
    faq: [
      { question: "Should I switch my home loan from MCLR to EBLR?", answer: "If your current MCLR-linked rate is higher than EBLR-linked rates and interest rates are stable or declining, switching can save money. However, consider the conversion fee (0.25-0.50% of outstanding) and that EBLR loans also pass rate hikes faster." },
      { question: "Can the bank change the spread in an EBLR loan?", answer: "The credit risk premium can be changed if your credit profile changes, but the bank's spread component is fixed at the time of loan sanction and cannot be increased during the loan tenure." },
      { question: "How quickly do repo rate cuts reflect in my EBLR loan?", answer: "EBLR-linked loans reset every 3 months (quarterly). So a repo rate cut will be reflected in your next reset date, which could be within 1-90 days depending on when the cut happens relative to your reset cycle." }
    ]
  },
  "mudra-loan": {
    contentHTML: `<h3>What is a Mudra Loan?</h3><p><strong>Mudra Loan</strong> is a government-backed business loan under the <strong>Pradhan Mantri MUDRA Yojana (PMMY)</strong>, launched in 2015. It provides collateral-free loans up to ₹10 lakh to micro and small enterprises, helping small business owners, artisans, and self-employed individuals start or expand their businesses.</p><h3>Mudra Loan Categories</h3><table><thead><tr><th>Category</th><th>Loan Amount</th><th>Stage</th></tr></thead><tbody><tr><td><strong>Shishu</strong></td><td>Up to ₹50,000</td><td>Starting / early-stage business</td></tr><tr><td><strong>Kishore</strong></td><td>₹50,001 – ₹5,00,000</td><td>Growing business seeking expansion</td></tr><tr><td><strong>Tarun</strong></td><td>₹5,00,001 – ₹10,00,000</td><td>Established business scaling up</td></tr></tbody></table><h3>Key Features</h3><ul><li><strong>No collateral required</strong></li><li>Available from all public sector banks, private banks, and MFIs</li><li>No processing fee for Shishu category</li><li>Repayment tenure: up to 5 years</li><li>Interest rate: 7.30% – 12% (varies by lender and category)</li></ul>`,
    faq: [
      { question: "Who is eligible for a Mudra Loan?", answer: "Any Indian citizen running or starting a non-farm, non-corporate micro or small enterprise is eligible. This includes shopkeepers, vendors, artisans, food service units, repair shops, machine operators, and small manufacturers. The enterprise should not be a subsidiary of any corporate entity." },
      { question: "Is Mudra Loan interest-free?", answer: "No, Mudra Loans are not interest-free. Interest rates range from 7.30% to 12% depending on the lender, borrower profile, and loan category (Shishu/Kishore/Tarun). However, they are significantly lower than typical unsecured business loans." },
      { question: "Can I get a Mudra Loan to start a new business?", answer: "Yes, Mudra Loans under the Shishu category (up to ₹50,000) are specifically designed for startup/early-stage businesses. You will need to submit a business plan along with your application, but collateral is not required." }
    ]
  },
  "credit-score": {
    contentHTML: `<h3>What is a Credit Score?</h3><p>A <strong>credit score</strong> is a three-digit number (300–900 in India) that represents your creditworthiness based on your credit history. In India, four bureaus issue credit scores: <strong>CIBIL (TransUnion)</strong>, <strong>Experian</strong>, <strong>Equifax</strong>, and <strong>CRIF High Mark</strong>. CIBIL Score is the most widely used by lenders.</p><h3>Credit Score vs. CIBIL Score</h3><table><thead><tr><th>Feature</th><th>Credit Score (Generic)</th><th>CIBIL Score</th></tr></thead><tbody><tr><td>Issuer</td><td>Any of 4 bureaus</td><td>TransUnion CIBIL only</td></tr><tr><td>Range</td><td>300-900</td><td>300-900</td></tr><tr><td>Most used by banks</td><td>Varies</td><td>Yes — most widely used</td></tr></tbody></table><h3>How to Check Your Credit Score for Free</h3><ul><li><strong>CIBIL:</strong> cibil.com (1 free report per year)</li><li><strong>RBI mandate:</strong> All bureaus must provide 1 free report per year</li><li><strong>Third-party apps:</strong> Paytm, PhonePe, BankBazaar offer free score checks</li></ul>`,
    faq: [
      { question: "Does checking my own credit score lower it?", answer: "No, checking your own credit score is a 'soft inquiry' and does not affect your score. Only 'hard inquiries' — when lenders check your score for a loan application — can temporarily lower it by 5-10 points." },
      { question: "How long does it take to improve a credit score?", answer: "Significant improvement typically takes 6-12 months of consistent on-time payments, low credit utilization, and no new loan applications. If you have a default or write-off, it stays on your report for 7 years." },
      { question: "Can I get a loan with a credit score below 650?", answer: "It is difficult but possible. Some NBFCs and fintech lenders offer loans to borrowers with lower scores, but at significantly higher interest rates (18-36%). You may also need a co-borrower or guarantor with a better score." }
    ]
  },
  "emi-bounce": {
    contentHTML: `<h3>What is an EMI Bounce?</h3><p>An <strong>EMI bounce</strong> occurs when your scheduled EMI payment fails because of insufficient funds in your linked bank account. This is treated as a payment default and triggers penalties from both your bank and your lender.</p><h3>Consequences of EMI Bounce</h3><table><thead><tr><th>Consequence</th><th>Details</th></tr></thead><tbody><tr><td><strong>Bounce charges</strong></td><td>₹300–₹1,000 per bounce (from your bank)</td></tr><tr><td><strong>Late payment fee</strong></td><td>1-2% of EMI amount (from lender)</td></tr><tr><td><strong>CIBIL impact</strong></td><td>Score drops 50-100 points for a single bounce</td></tr><tr><td><strong>Repeated bounces</strong></td><td>Loan may be classified as NPA after 90 days</td></tr></tbody></table><h3>How to Avoid EMI Bounces</h3><ul><li>Set up <strong>auto-debit</strong> (Standing Instruction / NACH mandate)</li><li>Maintain a buffer of 2-3 EMIs in your account</li><li>Set calendar reminders 2-3 days before EMI due date</li><li>If facing cash crunch, contact lender for restructuring <strong>before</strong> the bounce</li></ul>`,
    faq: [
      { question: "How much does an EMI bounce affect my CIBIL score?", answer: "A single EMI bounce can reduce your CIBIL score by 50-100 points. Multiple bounces in succession can cause an even steeper decline and result in the loan being flagged as a default, making it extremely difficult to get future loans." },
      { question: "What should I do immediately after an EMI bounce?", answer: "Deposit sufficient funds in your account and contact your lender immediately. Request them to re-attempt the EMI deduction. Pay any bounce charges and late fees promptly. Document the communication in case of disputes." },
      { question: "Can I reverse the credit score damage from an EMI bounce?", answer: "The bounce record stays on your credit report for 24-36 months. However, consistent on-time payments after the bounce will gradually improve your score. It typically takes 6-12 months of perfect payment behavior to recover." }
    ]
  },
  "co-borrower": {
    contentHTML: `<h3>What is a Co-Borrower?</h3><p>A <strong>co-borrower</strong> is a person who jointly applies for and takes a loan with the primary borrower. Both are equally responsible for repaying the loan and both names appear on the loan agreement. Co-borrowers are common in home loans, especially among spouses.</p><h3>Co-Borrower vs. Guarantor</h3><table><thead><tr><th>Feature</th><th>Co-Borrower</th><th>Guarantor</th></tr></thead><tbody><tr><td>Ownership rights</td><td>Can be co-owner of property</td><td>No ownership rights</td></tr><tr><td>Loan repayment</td><td>Equally responsible from Day 1</td><td>Liable only if borrower defaults</td></tr><tr><td>Tax benefits</td><td>Both can claim deductions</td><td>No tax benefits</td></tr><tr><td>Credit report impact</td><td>Loan appears on both reports</td><td>Appears as contingent liability</td></tr></tbody></table><h3>Benefits of Adding a Co-Borrower</h3><ul><li><strong>Higher loan eligibility</strong> — combined income considered</li><li><strong>Tax benefits</strong> — both can claim Sec 80C and Sec 24(b) deductions</li><li>Lower interest rate if co-borrower is female (some banks offer 0.05% concession)</li></ul>`,
    faq: [
      { question: "Can anyone be a co-borrower on a home loan?", answer: "Banks typically accept only close family members as co-borrowers: spouse, parents, siblings, or children. The co-borrower must be a co-owner of the property in most cases. Friends or business partners are generally not accepted." },
      { question: "Do both co-borrowers get tax benefits?", answer: "Yes, if both co-borrowers are co-owners and both contribute to EMI repayment, each can independently claim home loan tax benefits under Section 80C (principal, up to ₹1.5L each) and Section 24(b) (interest, up to ₹2L each), effectively doubling the total deductions." },
      { question: "What happens to the loan if one co-borrower dies?", answer: "The surviving co-borrower becomes solely responsible for repaying the remaining loan. This is why lenders strongly recommend joint home loan borrowers to take life insurance cover equal to the loan amount." }
    ]
  },
  "guarantor": {
    contentHTML: `<h3>What is a Loan Guarantor?</h3><p>A <strong>guarantor</strong> is a person who promises to repay a loan if the primary borrower defaults. Unlike a co-borrower, a guarantor does not have ownership rights over the financed asset and is only liable if the borrower fails to pay. Banks may require a guarantor if the borrower's income or credit score is insufficient.</p><h3>Guarantor's Obligations</h3><table><thead><tr><th>Aspect</th><th>Details</th></tr></thead><tbody><tr><td><strong>When liable</strong></td><td>Only after borrower defaults and lender initiates recovery</td></tr><tr><td><strong>Credit report</strong></td><td>Loan appears as contingent liability; default affects guarantor's CIBIL</td></tr><tr><td><strong>Legal risk</strong></td><td>Legal action possible against guarantor for recovery</td></tr><tr><td><strong>Release</strong></td><td>Released only when loan is fully repaid or lender agrees</td></tr></tbody></table><h3>Think Before Becoming a Guarantor</h3><ul><li>Your credit score will be affected if the borrower defaults</li><li>The loan appears on your credit report as a contingent liability</li><li>It may reduce your own loan eligibility</li><li>You may be legally pursued for the full outstanding amount</li></ul>`,
    faq: [
      { question: "Can a guarantor's property be seized if the borrower defaults?", answer: "Yes, if the bank exhausts recovery options against the borrower, it can legally pursue the guarantor. While personal property seizure depends on the loan type and guarantee terms, the guarantor's bank accounts can be attached and legal proceedings initiated." },
      { question: "How does being a guarantor affect my own loan eligibility?", answer: "The guaranteed loan appears as a contingent liability on your credit report. Banks may factor this into your debt-to-income ratio, potentially reducing the loan amount you can get for yourself." },
      { question: "Can I remove myself as a guarantor?", answer: "You can only be released as a guarantor if the borrower finds a replacement guarantor acceptable to the bank, or if the loan is fully repaid. You cannot unilaterally withdraw from a guarantee once the loan is disbursed." }
    ]
  },
  "disbursement": {
    contentHTML: `<h3>What is Loan Disbursement?</h3><p><strong>Disbursement</strong> is the actual release of loan funds from the lender to the borrower or the seller (in case of property/vehicle purchase). It occurs after all documentation, verification, and legal formalities are completed.</p><h3>Types of Disbursement</h3><table><thead><tr><th>Type</th><th>Used For</th><th>How It Works</th></tr></thead><tbody><tr><td><strong>Full Disbursement</strong></td><td>Personal loans, car loans</td><td>Entire loan amount released at once</td></tr><tr><td><strong>Partial/Tranche</strong></td><td>Home loans (under-construction)</td><td>Released in stages as construction progresses</td></tr></tbody></table><h3>What Happens Before Disbursement</h3><ul><li>KYC and document verification</li><li>Property legal and technical inspection (for home loans)</li><li>Loan sanction letter issued</li><li>Loan agreement and documents signed</li><li>Post-dated cheques or NACH mandate submitted</li><li>Insurance (if required) arranged</li></ul>`,
    faq: [
      { question: "How long does loan disbursement take after approval?", answer: "Personal loans: 1-3 days. Car loans: 1-5 days. Home loans: 7-15 days after all documents are in order. Under-construction home loans may take longer as disbursement happens in tranches linked to construction milestones." },
      { question: "What is partial disbursement in home loans?", answer: "For under-construction properties, banks release the loan in tranches (partial disbursement) based on the construction stage. You pay pre-EMI interest only on the disbursed amount until full disbursement, after which your regular EMI begins." },
      { question: "Can a bank cancel disbursement after loan approval?", answer: "Yes, a bank can cancel or hold disbursement if discrepancies are found during final verification, the property has legal issues, or your financial situation changes significantly (like job loss) between sanction and disbursement." }
    ]
  },
  "pre-emi-interest": {
    contentHTML: `<h3>What is Pre-EMI Interest?</h3><p><strong>Pre-EMI interest</strong> is the interest charged on the disbursed portion of a home loan before the full loan amount is released (applicable for under-construction properties). During this phase, you pay only the interest component — the principal repayment (full EMI) begins only after the entire loan is disbursed.</p><h3>Pre-EMI vs. Full EMI</h3><table><thead><tr><th>Feature</th><th>Pre-EMI</th><th>Full EMI</th></tr></thead><tbody><tr><td>What you pay</td><td>Interest only on disbursed amount</td><td>Principal + Interest on full loan</td></tr><tr><td>Monthly payment</td><td>Lower (only interest)</td><td>Higher (full EMI)</td></tr><tr><td>Principal reduction</td><td>None</td><td>Yes, with each EMI</td></tr><tr><td>Total interest cost</td><td>Higher over loan life</td><td>Lower over loan life</td></tr></tbody></table><h3>Should You Choose Pre-EMI or Full EMI?</h3><p>If you can afford it, opting for <strong>full EMI from the start</strong> (on the disbursed amount) is better because you begin repaying principal immediately, reducing the total interest over the loan tenure. Pre-EMI is essentially "dead money" — pure interest with no principal reduction.</p>`,
    faq: [
      { question: "Can I claim tax benefits on pre-EMI interest?", answer: "Yes, the total pre-EMI interest paid during the construction period can be claimed as a deduction under Section 24(b) in 5 equal instalments starting from the year of possession/completion. This is in addition to the regular home loan interest deduction." },
      { question: "Is it better to pay pre-EMI or full EMI for under-construction property?", answer: "Full EMI is financially better because you start reducing the principal immediately. However, pre-EMI offers lower monthly outgo during the construction phase, which may help if you're also paying rent. Choose based on your cash flow situation." },
      { question: "How is pre-EMI interest calculated?", answer: "Pre-EMI = (Disbursed Amount × Annual Interest Rate) ÷ 12. For example, if ₹20 lakhs is disbursed at 8.5%, your monthly pre-EMI = (20,00,000 × 0.085) ÷ 12 = ₹14,167. This changes each time a new tranche is disbursed." }
    ]
  },
  "sanction-letter": {
    contentHTML: `<h3>What is a Loan Sanction Letter?</h3><p>A <strong>sanction letter</strong> is an official document issued by a bank or financial institution after approving your loan application. It serves as a formal offer containing all the terms and conditions of the loan. The sanction letter is not the final loan agreement — it is an approval in principle.</p><h3>What a Sanction Letter Contains</h3><table><thead><tr><th>Detail</th><th>Description</th></tr></thead><tbody><tr><td><strong>Loan amount</strong></td><td>Maximum amount approved</td></tr><tr><td><strong>Interest rate</strong></td><td>Rate offered (fixed/floating + benchmark)</td></tr><tr><td><strong>Tenure</strong></td><td>Repayment period in months</td></tr><tr><td><strong>EMI amount</strong></td><td>Indicative monthly instalment</td></tr><tr><td><strong>Conditions</strong></td><td>Documents required, insurance, guarantor if needed</td></tr><tr><td><strong>Validity</strong></td><td>Usually 6 months from date of issue</td></tr></tbody></table><h3>Important Points</h3><ul><li>A sanction letter is <strong>not a guarantee of disbursement</strong> — final disbursement is subject to property verification and document completion</li><li>You can <strong>negotiate</strong> the terms in the sanction letter before accepting</li><li>Sanction letters from multiple banks help you <strong>compare offers</strong></li></ul>`,
    faq: [
      { question: "How long is a loan sanction letter valid?", answer: "A loan sanction letter is typically valid for 6 months from the date of issue. If you don't complete the loan process within this period, you may need to reapply, and the terms (interest rate, loan amount) may change." },
      { question: "Can I negotiate the terms in a sanction letter?", answer: "Yes, the sanction letter is a starting offer and many terms are negotiable. Interest rate, processing fee, and insurance requirements can often be negotiated, especially if you have competing offers from other banks." },
      { question: "Is a sanction letter the same as a loan agreement?", answer: "No. A sanction letter is an approval-in-principle with the proposed terms. The loan agreement is the final legally binding document signed at the time of disbursement. Terms in the final agreement should match the sanction letter." }
    ]
  },
  "noc": {
    contentHTML: `<h3>What is a Loan NOC?</h3><p>A <strong>No Objection Certificate (NOC)</strong> is an official document issued by the lender after a loan is fully repaid, confirming that the borrower has no outstanding dues. It releases the lender's claim (lien) on the pledged asset and is essential for transferring property ownership or getting original documents back from the bank.</p><h3>Why NOC Is Important</h3><table><thead><tr><th>Reason</th><th>Details</th></tr></thead><tbody><tr><td><strong>Property sale</strong></td><td>Cannot sell a property without NOC from the bank</td></tr><tr><td><strong>RC transfer</strong></td><td>Vehicle RC endorsement removal requires NOC</td></tr><tr><td><strong>Credit report</strong></td><td>Ensures loan shows as "closed" on CIBIL</td></tr><tr><td><strong>Document retrieval</strong></td><td>Bank returns original property documents with NOC</td></tr></tbody></table><h3>Timeline for Getting NOC</h3><ul><li><strong>Home Loan:</strong> 15-30 days after final payment</li><li><strong>Vehicle Loan:</strong> 7-15 days</li><li><strong>Personal Loan:</strong> 3-7 days</li></ul><p>Always follow up within 30 days of final payment. Some banks automatically issue the NOC; others require you to apply.</p>`,
    faq: [
      { question: "What should I do if the bank delays issuing the NOC?", answer: "If the bank delays beyond 30 days, send a written complaint to the bank's grievance redressal department. If unresolved within 30 days, escalate to the Banking Ombudsman (RBI). Banks are legally obligated to issue the NOC and return original documents after loan closure." },
      { question: "What documents should I receive along with the NOC?", answer: "Along with the NOC, the bank should return: all original property documents (sale deed, title deed, building plan approvals), original loan agreement with an 'account closed' stamp, and a lien release letter for the sub-registrar's office." },
      { question: "Do I need to update the NOC with any government office?", answer: "For home loans, you should register the lien removal with the sub-registrar's office where the property is registered. For vehicle loans, update the RTO to remove the bank's endorsement from the RC. These steps ensure no encumbrance shows on official records." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' loan terms (batch 2)');
