const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "rupee-cost-averaging": {
    contentHTML: `<h3>What is Rupee Cost Averaging?</h3><p><strong>Rupee cost averaging</strong> is an investment strategy where you invest a fixed amount at regular intervals regardless of market conditions. When prices are low, you buy more units; when prices are high, you buy fewer units. Over time, this averages out your cost per unit, reducing the impact of market volatility.</p><h3>How It Works</h3><table><thead><tr><th>Month</th><th>NAV (₹)</th><th>Investment</th><th>Units</th></tr></thead><tbody><tr><td>Jan</td><td>100</td><td>₹5,000</td><td>50.0</td></tr><tr><td>Feb</td><td>80</td><td>₹5,000</td><td>62.5</td></tr><tr><td>Mar</td><td>120</td><td>₹5,000</td><td>41.7</td></tr><tr><td>Apr</td><td>90</td><td>₹5,000</td><td>55.6</td></tr><tr><td><strong>Total</strong></td><td><strong>Avg NAV: 97.5</strong></td><td><strong>₹20,000</strong></td><td><strong>209.8 (Avg cost: ₹95.3)</strong></td></tr></tbody></table><p>Your average cost (₹95.3) is lower than the simple average NAV (₹97.5) because you bought more units when prices were low.</p>`,
    faq: [
      { question: "Does rupee cost averaging guarantee profits?", answer: "No, it does not guarantee profits. If the market experiences a prolonged decline, your investments may still lose value. However, it reduces the risk of investing a large sum at the wrong time and smooths out volatility over the long term." },
      { question: "Is SIP the same as rupee cost averaging?", answer: "SIP (Systematic Investment Plan) is the practical implementation of rupee cost averaging in mutual funds. By investing a fixed amount monthly via SIP, you automatically benefit from rupee cost averaging without needing to time the market." },
      { question: "Is rupee cost averaging better than lump sum investing?", answer: "Historical data shows that lump sum investing often outperforms rupee cost averaging in bull markets, but rupee cost averaging performs better in volatile or declining markets. For most salaried individuals, rupee cost averaging through SIP is more practical and emotionally easier." }
    ]
  },
  "maturity-value": {
    contentHTML: `<h3>What is Maturity Value?</h3><p><strong>Maturity value</strong> is the total amount you receive when a financial instrument (FD, RD, PPF, insurance policy) reaches the end of its term. It includes your original investment (principal) plus all accumulated interest or returns.</p><h3>Maturity Value Formulas</h3><table><thead><tr><th>Instrument</th><th>Formula</th></tr></thead><tbody><tr><td><strong>FD</strong></td><td>A = P × (1 + r/n)<sup>nt</sup></td></tr><tr><td><strong>RD</strong></td><td>A = P × [(1+r/n)<sup>nt</sup> − 1] / (r/n) × (1+r/n)</td></tr><tr><td><strong>PPF</strong></td><td>Compound interest at annual compounding over 15 years</td></tr></tbody></table><h3>Example — FD Maturity</h3><p>₹5,00,000 FD at 7% for 5 years (quarterly compounding): Maturity Value = ₹5,00,000 × (1 + 0.07/4)^(4×5) = <strong>₹7,09,260</strong></p>`,
    faq: [
      { question: "Is maturity value the same as the returns on investment?", answer: "No. Maturity value is the total amount you receive at maturity (principal + interest/returns). The 'return' or 'gain' is the maturity value minus your total investment. For example, if you invest ₹5L and maturity value is ₹7L, your return is ₹2L." },
      { question: "Is the maturity value of FD taxable?", answer: "The interest component of FD maturity is taxable as per your income tax slab. The principal portion is not taxed. TDS is deducted during the FD tenure if annual interest exceeds ₹40,000." },
      { question: "Can I calculate maturity value for SIP investments?", answer: "Since SIP returns are market-linked, you can only estimate maturity value by assuming an expected return rate (CAGR). Use: FV = P × [(1+r)^n − 1] / r × (1+r), where P is monthly SIP, r is monthly return rate, and n is number of months." }
    ]
  },
  "dividend": {
    contentHTML: `<h3>What is a Dividend?</h3><p>A <strong>dividend</strong> is a portion of a company's profits distributed to its shareholders. In India, companies declare dividends on a per-share basis (e.g., ₹15 per share) and are approved by the board of directors and shareholders at the Annual General Meeting.</p><h3>Key Dividend Metrics</h3><table><thead><tr><th>Metric</th><th>Formula</th><th>What It Tells You</th></tr></thead><tbody><tr><td><strong>Dividend Yield</strong></td><td>(Annual Dividend / Share Price) × 100</td><td>Income return on stock price</td></tr><tr><td><strong>Payout Ratio</strong></td><td>(Dividends / Net Profit) × 100</td><td>What % of profits are distributed</td></tr></tbody></table><h3>Dividend Taxation in India (Post-2020)</h3><ul><li>Dividends are taxable in the hands of the <strong>investor</strong> at their income tax slab rate</li><li>TDS of 10% deducted if annual dividend exceeds ₹5,000</li><li>Dividend from mutual funds is also taxable at slab rate</li></ul>`,
    faq: [
      { question: "Are dividends taxable in India?", answer: "Yes, since April 2020, dividends are taxable in the hands of the investor at their applicable income tax slab rate. Companies deduct TDS at 10% if dividend income exceeds ₹5,000 in a financial year." },
      { question: "What is the difference between dividend and growth mutual fund options?", answer: "In the dividend option, the fund pays out profits periodically (reducing NAV). In the growth option, profits are reinvested in the fund (increasing NAV). For long-term wealth creation, the growth option is tax-efficient and earns compound returns." },
      { question: "How often do Indian companies pay dividends?", answer: "Most Indian companies pay dividends annually. Some pay interim dividends (mid-year) in addition to final dividends. Companies are not obligated to pay dividends — it depends on profitability and the board's decision." }
    ]
  },
  "benchmark": {
    contentHTML: `<h3>What is a Benchmark?</h3><p>A <strong>benchmark</strong> is a standard or index against which the performance of a mutual fund or investment portfolio is measured. If a fund consistently outperforms its benchmark, it is generating "alpha" (excess returns); if it underperforms, investors may be better off with an index fund.</p><h3>Common Benchmarks in India</h3><table><thead><tr><th>Benchmark</th><th>Used For</th><th>Tracks</th></tr></thead><tbody><tr><td><strong>Nifty 50</strong></td><td>Large-cap equity funds</td><td>Top 50 NSE stocks</td></tr><tr><td><strong>Sensex 30</strong></td><td>Large-cap funds</td><td>Top 30 BSE stocks</td></tr><tr><td><strong>Nifty Midcap 150</strong></td><td>Mid-cap funds</td><td>Stocks ranked 101-250</td></tr><tr><td><strong>Nifty Smallcap 250</strong></td><td>Small-cap funds</td><td>Stocks beyond rank 250</td></tr><tr><td><strong>CRISIL Composite Bond</strong></td><td>Debt funds</td><td>Government + corporate bonds</td></tr></tbody></table>`,
    faq: [
      { question: "Why is benchmark comparison important?", answer: "Without a benchmark, a fund's 12% return has no context. If the benchmark returned 15%, the fund actually underperformed. Benchmark comparison reveals whether the fund manager is adding value or if you'd be better off with a low-cost index fund." },
      { question: "What does it mean when a fund 'beats' its benchmark?", answer: "When a fund beats its benchmark, it has delivered higher returns than the index it is measured against. This excess return is called 'alpha.' A fund that consistently generates positive alpha is considered well-managed." },
      { question: "Can I invest directly in a benchmark index?", answer: "Yes, through index funds or ETFs (Exchange Traded Funds) that replicate the benchmark. For example, a Nifty 50 index fund gives you exactly the Nifty 50 returns minus a very small expense ratio." }
    ]
  },
  "demat-account": {
    contentHTML: `<h3>What is a Demat Account?</h3><p>A <strong>Demat (Dematerialized) Account</strong> holds your shares and securities in electronic form, replacing physical share certificates. In India, two depositories manage demat accounts: <strong>NSDL</strong> (National Securities Depository Limited) and <strong>CDSL</strong> (Central Depository Services Limited).</p><h3>Demat vs. Trading Account</h3><table><thead><tr><th>Feature</th><th>Demat Account</th><th>Trading Account</th></tr></thead><tbody><tr><td>Purpose</td><td>Holds shares/securities</td><td>Executes buy/sell orders</td></tr><tr><td>Analogy</td><td>Bank locker</td><td>Transaction counter</td></tr><tr><td>Required for</td><td>Holding stocks, bonds, ETFs</td><td>Buying/selling on stock exchange</td></tr></tbody></table><h3>Documents Required</h3><ul><li>PAN Card (mandatory)</li><li>Aadhaar for e-KYC</li><li>Bank account details</li><li>Passport-size photograph</li><li>Account can be opened online in 15-30 minutes</li></ul>`,
    faq: [
      { question: "Is a demat account required for mutual fund investments?", answer: "No, a demat account is not required for investing in mutual funds. You can invest directly through AMC websites, apps, or aggregator platforms. However, a demat account is required if you want to buy ETFs (Exchange Traded Funds) or mutual fund units on the stock exchange." },
      { question: "What are the charges for a demat account?", answer: "Charges vary by broker: account opening (₹0-500), annual maintenance (₹300-750/year, many brokers waive for the first year), and transaction charges per trade. Discount brokers like Zerodha and Groww often have zero account opening fees." },
      { question: "What happens to my demat account if I don't use it?", answer: "If your demat account has no transactions and no holdings for 12 months, it may be classified as 'inactive' or 'dormant.' You can reactivate it by submitting a reactivation request with updated KYC documents to your depository participant." }
    ]
  },
  "kyc": {
    contentHTML: `<h3>What is KYC?</h3><p><strong>Know Your Customer (KYC)</strong> is a verification process mandated by SEBI and RBI to confirm the identity and address of investors and account holders. KYC is required for opening demat accounts, trading accounts, mutual fund investments, bank accounts, and insurance policies.</p><h3>Types of KYC in India</h3><table><thead><tr><th>Type</th><th>Process</th><th>Time</th></tr></thead><tbody><tr><td><strong>e-KYC</strong></td><td>Online via Aadhaar OTP</td><td>5-10 minutes</td></tr><tr><td><strong>In-Person Verification (IPV)</strong></td><td>Video call or branch visit</td><td>15-30 minutes</td></tr><tr><td><strong>CKYC</strong></td><td>Central KYC (once done, valid for all financial institutions)</td><td>Paper-based</td></tr></tbody></table><h3>KYC for Mutual Funds</h3><ul><li>Complete KYC through SEBI-registered KRAs (KYC Registration Agencies)</li><li>Once done, your KYC is valid across all AMCs — no need to repeat</li><li>Check KYC status at <strong>kra.ndml.in</strong> or <strong>cvlkra.com</strong></li></ul>`,
    faq: [
      { question: "Is KYC a one-time process?", answer: "For mutual funds, yes — once KYC is completed with any SEBI-registered KRA, it is valid across all AMCs. For bank accounts and demat accounts, periodic re-KYC may be required every 5-10 years or when there are changes in your personal information." },
      { question: "Can I invest in mutual funds without KYC?", answer: "No, KYC is mandatory for all mutual fund investments in India as per SEBI regulations. However, the process is very simple now — you can complete e-KYC online in under 10 minutes using your Aadhaar and PAN." },
      { question: "What documents are needed for KYC?", answer: "Mandatory: PAN card and Aadhaar. For e-KYC, just PAN and Aadhaar with OTP verification is sufficient. For full KYC, you may additionally need address proof, passport-size photo, and in-person/video verification." }
    ]
  },
  "lock-in-period": {
    contentHTML: `<h3>What is Lock-in Period?</h3><p>A <strong>lock-in period</strong> is the minimum duration for which an investment must be held before you can redeem or withdraw it. During this period, partial or full withdrawal is either prohibited or attracts penalties.</p><h3>Lock-in Periods for Common Investments</h3><table><thead><tr><th>Investment</th><th>Lock-in Period</th></tr></thead><tbody><tr><td><strong>ELSS Mutual Funds</strong></td><td>3 years</td></tr><tr><td><strong>Tax-Saving FD</strong></td><td>5 years</td></tr><tr><td><strong>PPF</strong></td><td>15 years (partial withdrawal after 7 years)</td></tr><tr><td><strong>NPS Tier I</strong></td><td>Until age 60</td></tr><tr><td><strong>NSC</strong></td><td>5 years</td></tr><tr><td><strong>Sukanya Samriddhi</strong></td><td>Until girl child turns 21</td></tr><tr><td><strong>Regular Mutual Funds</strong></td><td>None (exit load may apply)</td></tr></tbody></table>`,
    faq: [
      { question: "Can I withdraw money during the lock-in period?", answer: "For most instruments, withdrawal during lock-in is not allowed. Exceptions include PPF (partial withdrawal after 7 years), NPS (partial withdrawal after 3 years for specific purposes), and emergency withdrawals from EPF. FDs can be broken with penalty." },
      { question: "Does lock-in period mean I cannot sell ELSS units for 3 years?", answer: "Correct. ELSS units have a mandatory 3-year lock-in from the date of allotment. If you invest via SIP, each monthly instalment has its own 3-year lock-in. After 3 years, units are automatically unlocked." },
      { question: "Is lock-in period the same as exit load?", answer: "No. Lock-in period is a hard restriction — you cannot redeem at all. Exit load is a charge for redeeming before a certain period, but you can still redeem if needed. For example, regular equity mutual funds have no lock-in but charge 1% exit load if redeemed within 1 year." }
    ]
  },
  "exit-load": {
    contentHTML: `<h3>What is Exit Load?</h3><p><strong>Exit load</strong> is a fee charged by mutual fund companies when you redeem (sell) your units before a specified period. It discourages short-term trading and ensures long-term investors are not penalized by frequent inflows/outflows.</p><h3>Typical Exit Loads</h3><table><thead><tr><th>Fund Type</th><th>Exit Load</th><th>Applicable Period</th></tr></thead><tbody><tr><td><strong>Equity Funds</strong></td><td>1%</td><td>If redeemed within 1 year</td></tr><tr><td><strong>Liquid Funds</strong></td><td>0-0.007%</td><td>If redeemed within 7 days</td></tr><tr><td><strong>ELSS</strong></td><td>NIL</td><td>Lock-in is 3 years (no exit load after)</td></tr><tr><td><strong>Debt Funds</strong></td><td>0-0.50%</td><td>Varies by scheme</td></tr></tbody></table><h3>How Exit Load Is Calculated</h3><p>Exit load is charged on the <strong>redemption amount</strong>. If you redeem ₹1,00,000 from an equity fund within 1 year, exit load = ₹1,000 (1%). After 1 year, exit load = ₹0.</p>`,
    faq: [
      { question: "How can I avoid paying exit load?", answer: "Simply hold your mutual fund investment for the specified period (usually 1 year for equity funds). After this period, the exit load is zero. If you need liquidity, invest in liquid funds, overnight funds, or money market funds which have negligible exit loads." },
      { question: "Is exit load applicable on SIP investments?", answer: "Yes, each SIP instalment has its own exit load period. For example, if the exit load period is 1 year, your January SIP is exit-load-free from the following January, your February SIP from the following February, and so on." },
      { question: "Where does the exit load money go?", answer: "Exit load collected is credited back to the mutual fund scheme, benefiting the remaining investors. It is not revenue for the AMC." }
    ]
  },
  "liquidity": {
    contentHTML: `<h3>What is Liquidity?</h3><p><strong>Liquidity</strong> refers to how quickly and easily an asset can be converted into cash without significantly affecting its price. Cash is the most liquid asset; real estate is among the least liquid.</p><h3>Liquidity of Common Investments</h3><table><thead><tr><th>Investment</th><th>Liquidity</th><th>Time to Cash</th></tr></thead><tbody><tr><td><strong>Savings Account</strong></td><td>Very High</td><td>Instant</td></tr><tr><td><strong>Liquid Mutual Funds</strong></td><td>Very High</td><td>T+1 day</td></tr><tr><td><strong>Stocks (Large Cap)</strong></td><td>High</td><td>T+1 day</td></tr><tr><td><strong>FD (with penalty)</strong></td><td>Moderate</td><td>1-2 days</td></tr><tr><td><strong>PPF</strong></td><td>Low</td><td>15-year lock-in</td></tr><tr><td><strong>Real Estate</strong></td><td>Very Low</td><td>Weeks to months</td></tr></tbody></table>`,
    faq: [
      { question: "Why is liquidity important in financial planning?", answer: "Liquidity ensures you can access funds during emergencies without significant loss. Financial planners recommend keeping 3-6 months of expenses in highly liquid assets (savings account or liquid funds) as an emergency fund before investing in less-liquid instruments." },
      { question: "Does higher liquidity mean lower returns?", answer: "Generally, yes. More liquid instruments (savings accounts, liquid funds) tend to offer lower returns compared to less liquid ones (PPF, FDs, real estate). This is called the 'liquidity premium' — you earn higher returns as compensation for locking money for longer." },
      { question: "What is the most liquid investment in India?", answer: "A savings bank account is the most liquid as you can withdraw cash instantly via ATM or UPI. Among investments, liquid mutual funds are the most liquid — redemptions are processed within 24 hours (T+1), and some offer instant redemption up to ₹50,000." }
    ]
  },
  "diversification": {
    contentHTML: `<h3>What is Diversification?</h3><p><strong>Diversification</strong> is the strategy of spreading investments across different asset classes, sectors, geographies, and instruments to reduce risk. The idea is simple: don't put all your eggs in one basket.</p><h3>Levels of Diversification</h3><table><thead><tr><th>Level</th><th>Example</th><th>Risk Reduced</th></tr></thead><tbody><tr><td><strong>Asset Class</strong></td><td>Equity + Debt + Gold + Real Estate</td><td>Market risk</td></tr><tr><td><strong>Within Equity</strong></td><td>Large + Mid + Small Cap</td><td>Company-specific risk</td></tr><tr><td><strong>Sector</strong></td><td>Banking + IT + Pharma + FMCG</td><td>Sector risk</td></tr><tr><td><strong>Geography</strong></td><td>India + US + Emerging Markets</td><td>Country risk</td></tr></tbody></table><h3>Ideal Diversification Template (Indian Investor)</h3><ul><li><strong>Equity (60-70%):</strong> Multi-cap/flexi-cap mutual funds</li><li><strong>Debt (20-30%):</strong> PPF, FDs, debt mutual funds</li><li><strong>Gold (5-10%):</strong> Sovereign Gold Bonds or Gold ETFs</li></ul>`,
    faq: [
      { question: "How many stocks should I own for adequate diversification?", answer: "Research suggests that 15-25 stocks across different sectors provide adequate diversification for an individual portfolio. Beyond 30 stocks, the additional diversification benefit is minimal. Alternatively, invest in a diversified mutual fund that holds 40-60 stocks." },
      { question: "Can I be over-diversified?", answer: "Yes, this is called 'diworsification.' Holding too many funds with overlapping portfolios dilutes returns without meaningfully reducing risk. For mutual fund investors, 4-6 well-chosen funds across categories is sufficient." },
      { question: "Does diversification guarantee against losses?", answer: "No, diversification reduces risk but does not eliminate it. In extreme market events (like the 2008 financial crisis or COVID-19 crash), most asset classes can fall simultaneously. However, a diversified portfolio typically recovers faster and experiences smaller drawdowns." }
    ]
  },
  "power-of-compounding": {
    contentHTML: `<h3>What is the Power of Compounding?</h3><p>The <strong>power of compounding</strong> is the phenomenon where your investment earns returns not only on the original principal but also on the accumulated returns from previous periods. Over time, this creates an exponential growth curve, turning even small regular investments into substantial wealth.</p><h3>The Magic of Time</h3><table><thead><tr><th>SIP</th><th>Duration</th><th>Invested</th><th>Value at 12%</th><th>Gain</th></tr></thead><tbody><tr><td>₹5,000/mo</td><td>10 years</td><td>₹6,00,000</td><td>₹11,61,695</td><td>₹5,61,695</td></tr><tr><td>₹5,000/mo</td><td>20 years</td><td>₹12,00,000</td><td>₹49,95,740</td><td>₹37,95,740</td></tr><tr><td>₹5,000/mo</td><td>30 years</td><td>₹18,00,000</td><td>₹1,76,49,569</td><td>₹1,58,49,569</td></tr></tbody></table><p>Notice how the gain in the 3rd decade (₹1.27 crore) is nearly <strong>3.3x</strong> the gain in the first two decades combined. This is compounding in action — the longer you stay invested, the faster your money grows.</p>`,
    faq: [
      { question: "When is the best time to start investing for compounding?", answer: "As early as possible. A 25-year-old investing ₹5,000/month at 12% until 60 accumulates ₹1.76 crore. A 35-year-old doing the same accumulates only ₹49.95 lakh. The 10-year head start results in 3.5x more wealth despite investing only ₹6 lakh more." },
      { question: "Does compounding work on mutual fund SIPs?", answer: "Yes, mutual fund returns compound because unrealized gains are reinvested into the fund (in growth plans). Each unit you buy grows in value, and that growth itself generates further growth. This is why long-term SIP investors build significant wealth." },
      { question: "What is the Rule of 72 in relation to compounding?", answer: "The Rule of 72 is a quick formula to estimate how long it takes for an investment to double: Years to Double ≈ 72 ÷ Annual Return Rate. At 12% returns, your money doubles in approximately 6 years; at 8%, in 9 years." }
    ]
  },
  "real-returns": {
    contentHTML: `<h3>What are Real Returns?</h3><p><strong>Real returns</strong> are investment returns adjusted for inflation. They represent the actual increase in your purchasing power. If your investment earns 10% but inflation is 6%, your real return is approximately 4%.</p><h3>Formula</h3><p><strong>Real Return ≈ Nominal Return − Inflation Rate</strong></p><p>(Precise formula: Real Return = ((1 + Nominal) / (1 + Inflation)) − 1)</p><h3>Real Returns of Common Indian Investments</h3><table><thead><tr><th>Investment</th><th>Nominal Return</th><th>Inflation (~6%)</th><th>Real Return</th></tr></thead><tbody><tr><td><strong>Savings Account</strong></td><td>3-4%</td><td>6%</td><td><strong>−2 to −3%</strong></td></tr><tr><td><strong>FD</strong></td><td>6-7%</td><td>6%</td><td><strong>0 to 1%</strong></td></tr><tr><td><strong>PPF</strong></td><td>7.1%</td><td>6%</td><td><strong>~1%</strong></td></tr><tr><td><strong>Equity MF (long-term)</strong></td><td>12-15%</td><td>6%</td><td><strong>6-9%</strong></td></tr></tbody></table><p>Savings accounts and FDs barely keep up with inflation, meaning your <strong>purchasing power stays flat or erodes</strong>. Only equity and growth-oriented investments generate meaningful real returns.</p>`,
    faq: [
      { question: "Why are real returns more important than nominal returns?", answer: "Nominal returns tell you how much money you earned, but real returns tell you how much richer you actually became. If your FD earns 7% but inflation is 6%, you're only 1% richer in purchasing power. Your ₹1 lakh can buy only marginally more than before." },
      { question: "Which investments give the best real returns in India?", answer: "Historically, equity mutual funds (12-15% nominal, 6-9% real), direct stocks (varies widely), and real estate in Tier 1 cities have delivered the best real returns over 10+ year periods. Government-backed instruments like PPF provide modest real returns of 1-2%." },
      { question: "Can real returns be negative?", answer: "Yes. When inflation exceeds your investment's nominal return, your real return is negative. For example, money in a savings account earning 3.5% during a period of 6% inflation has a real return of −2.5%, meaning it is losing purchasing power." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' invest terms (batch 2)');
