const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "pan-card": {
    contentHTML: `<h3>What is a PAN Card?</h3><p><strong>Permanent Account Number (PAN)</strong> is a unique 10-character alphanumeric identifier issued by the Income Tax Department of India. It is mandatory for all financial transactions above certain thresholds and serves as the universal financial ID for taxpayers.</p><h3>Where PAN Is Mandatory</h3><table><thead><tr><th>Transaction</th><th>PAN Required If</th></tr></thead><tbody><tr><td>Opening bank account</td><td>Always</td></tr><tr><td>Property purchase/sale</td><td>Value exceeds ₹10 lakh</td></tr><tr><td>Vehicle purchase</td><td>Always (4-wheeler)</td></tr><tr><td>Cash deposit in bank</td><td>Above ₹50,000/day</td></tr><tr><td>FD opening</td><td>Above ₹50,000</td></tr><tr><td>Mutual fund investment</td><td>Always</td></tr><tr><td>Credit card application</td><td>Always</td></tr></tbody></table><h3>PAN Format</h3><p><strong>ABCDE1234F</strong> — First 5 letters (4th letter indicates entity type: P=Person, C=Company, H=HUF, F=Firm), 4 digits, 1 check letter.</p>`,
    faq: [
      { question: "How do I apply for a PAN card?", answer: "Apply online through NSDL (onlineservices.nsdl.com) or UTIITSL (pan.utiitsl.com) by filling Form 49A (for Indian citizens) or 49AA (for foreigners). Fee is approximately ₹110 for e-PAN and ₹1,020 for physical dispatch. e-PAN is issued within 48 hours of Aadhaar-based e-KYC." },
      { question: "Is PAN linked to Aadhaar mandatory?", answer: "Yes, linking PAN with Aadhaar is mandatory for all individual taxpayers. Failure to link results in PAN becoming 'inoperative,' which means you cannot use it for financial transactions and TDS will be deducted at a higher rate." },
      { question: "What happens if I have two PAN cards?", answer: "Having multiple PAN numbers is illegal. If you have been allotted two PANs, you must surrender the extra one by filling the PAN change request form. Failure to do so can attract a penalty of ₹10,000 under Section 272B of the Income Tax Act." }
    ]
  },
  "form-16": {
    contentHTML: `<h3>What is Form 16?</h3><p><strong>Form 16</strong> is a TDS certificate issued by employers to employees, certifying the salary paid and tax deducted during a financial year. It is the primary document used for filing income tax returns for salaried individuals.</p><h3>Parts of Form 16</h3><table><thead><tr><th>Part</th><th>Contains</th></tr></thead><tbody><tr><td><strong>Part A</strong></td><td>TAN of employer, PAN of employee, TDS deducted and deposited (quarterly breakup), assessment year</td></tr><tr><td><strong>Part B</strong></td><td>Detailed salary breakup, allowances, perquisites, deductions claimed (80C, 80D, 24b, HRA), taxable income, tax computed</td></tr></tbody></table><h3>Key Dates</h3><ul><li><strong>Employer must issue Form 16 by:</strong> June 15 each year</li><li><strong>For FY 2024-25:</strong> Form 16 should be issued by June 15, 2025</li><li><strong>ITR filing deadline:</strong> July 31 of the assessment year</li></ul>`,
    faq: [
      { question: "Can I file ITR without Form 16?", answer: "Yes, you can file ITR using salary slips, Form 26AS, and Annual Information Statement (AIS). Form 16 makes it easier but is not mandatory for filing. All the information in Form 16 is also available through the income tax e-filing portal." },
      { question: "What if my employer does not issue Form 16?", answer: "If your employer deducts TDS but does not issue Form 16 by June 15, you can file a complaint with the Income Tax Department or use Form 26AS (which shows all TDS deducted against your PAN) to file your ITR." },
      { question: "Do I get separate Form 16 if I changed jobs mid-year?", answer: "Yes, you will receive separate Form 16 from each employer. Both must be used while filing your ITR. Each employer deducts TDS based on the salary they paid, so the total TDS from both may be less than your actual liability for the combined income." }
    ]
  },
  "itr": {
    contentHTML: `<h3>What is ITR?</h3><p><strong>Income Tax Return (ITR)</strong> is a form filed with the Income Tax Department declaring your total income, deductions, and tax liability for a financial year. Filing ITR is mandatory if your income exceeds the basic exemption limit, and is recommended even otherwise for loan applications, visa processing, and carrying forward losses.</p><h3>ITR Form Types</h3><table><thead><tr><th>Form</th><th>Who Should File</th></tr></thead><tbody><tr><td><strong>ITR-1 (Sahaj)</strong></td><td>Salaried individuals (income up to ₹50L, one house property)</td></tr><tr><td><strong>ITR-2</strong></td><td>Individuals with capital gains, multiple properties, foreign income</td></tr><tr><td><strong>ITR-3</strong></td><td>Individuals with business/profession income</td></tr><tr><td><strong>ITR-4 (Sugam)</strong></td><td>Presumptive income scheme (Section 44AD/44ADA)</td></tr></tbody></table><h3>Important Deadlines</h3><ul><li><strong>Original filing:</strong> July 31 (non-audit), October 31 (audit)</li><li><strong>Belated filing:</strong> December 31 (with penalty)</li><li><strong>Revised return:</strong> December 31 of assessment year</li></ul>`,
    faq: [
      { question: "Who is required to file ITR in India?", answer: "ITR filing is mandatory if: (1) gross total income exceeds the basic exemption limit (₹2.5L/₹3L), (2) you want to claim a tax refund, (3) you hold assets or are a signing authority in accounts outside India, (4) your total TDS/TCS exceeds ₹25,000, or (5) your deposits in savings accounts exceed ₹50 lakh." },
      { question: "What is the penalty for late filing of ITR?", answer: "Under Section 234F: ₹5,000 if filed after due date but before December 31, ₹1,000 if income is below ₹5 lakh. Additionally, interest under Section 234A (1% per month on unpaid tax) and inability to carry forward capital losses apply." },
      { question: "Can I revise my ITR after filing?", answer: "Yes, you can file a revised return under Section 139(5) before December 31 of the assessment year or before the completion of assessment, whichever is earlier. There is no limit on the number of times you can revise." }
    ]
  },
  "new-tax-regime": {
    contentHTML: `<h3>What is the New Tax Regime?</h3><p>The <strong>New Tax Regime</strong> (introduced in Budget 2020, updated in Budget 2023 and 2024) offers lower income tax rates but removes most deductions and exemptions available in the old regime. It is now the <strong>default regime</strong> — you must actively opt out to choose the old regime.</p><h3>New vs. Old Regime Comparison</h3><table><thead><tr><th>Feature</th><th>New Regime</th><th>Old Regime</th></tr></thead><tbody><tr><td>Basic exemption</td><td>₹3,00,000</td><td>₹2,50,000</td></tr><tr><td>Standard deduction</td><td>₹75,000</td><td>₹50,000</td></tr><tr><td>Section 80C</td><td>Not available</td><td>Up to ₹1.5L</td></tr><tr><td>Section 80D</td><td>Not available</td><td>Up to ₹75,000</td></tr><tr><td>HRA exemption</td><td>Not available</td><td>Available</td></tr><tr><td>Section 24(b)</td><td>Not available (self-occupied)</td><td>Up to ₹2L</td></tr><tr><td>Rebate u/s 87A</td><td>Up to ₹7L income</td><td>Up to ₹5L income</td></tr></tbody></table>`,
    faq: [
      { question: "Is the new tax regime mandatory?", answer: "The new regime is the default, but it is not mandatory. Salaried individuals can choose between old and new regimes each year. Business/profession taxpayers who opt for old regime cannot switch back to new every year." },
      { question: "When should I choose the old regime over new?", answer: "The old regime is better if your total deductions (80C + 80D + HRA + 24b + NPS 80CCD + others) exceed approximately ₹3.75-4.25 lakh. Use an income tax calculator to compare the exact tax liability under both regimes." },
      { question: "Can I switch between old and new regime every year?", answer: "Salaried individuals (no business income) can switch between regimes every financial year while filing their ITR. Those with business income can switch from new to old only once in their lifetime — after that, the choice is locked." }
    ]
  },
  "standard-deduction": {
    contentHTML: `<h3>What is Standard Deduction?</h3><p><strong>Standard deduction</strong> is a flat deduction from gross salary that reduces your taxable income, without needing any investment or expense proof. It is available to all salaried employees and pensioners.</p><h3>Standard Deduction History</h3><table><thead><tr><th>Budget Year</th><th>Amount</th><th>Regime</th></tr></thead><tbody><tr><td>Budget 2018</td><td>₹40,000</td><td>Old regime</td></tr><tr><td>Budget 2019</td><td>₹50,000</td><td>Old regime</td></tr><tr><td>Budget 2023</td><td>₹50,000</td><td>Both old & new</td></tr><tr><td>Budget 2024</td><td>₹75,000</td><td>New regime only</td></tr></tbody></table><h3>How It Works</h3><p>Standard deduction is automatically reduced from your gross salary before computing taxable income. No documentation or proof of expenses is required. For example, if your gross salary is ₹10,00,000, taxable salary becomes ₹9,25,000 (under new regime with ₹75,000 standard deduction).</p>`,
    faq: [
      { question: "Is standard deduction available in both old and new tax regimes?", answer: "Yes, standard deduction is available in both regimes. However, the amount differs: ₹50,000 under the old regime and ₹75,000 under the new regime (as per Budget 2024)." },
      { question: "Do pensioners get standard deduction?", answer: "Yes, pensioners receiving pension from their former employer get the standard deduction. Family pensioners also get a deduction of ₹15,000 or 1/3rd of pension, whichever is lower." },
      { question: "Is standard deduction the same as Section 80C deduction?", answer: "No, they are completely separate. Standard deduction is a flat unconditional deduction from salary (no investment needed). Section 80C requires actual investments in eligible instruments like PPF, ELSS, etc. Both can be claimed together under the old regime." }
    ]
  },
  "tax-rebate-87a": {
    contentHTML: `<h3>What is Tax Rebate Under Section 87A?</h3><p><strong>Section 87A</strong> provides a rebate (direct reduction in tax payable) for resident individuals whose total taxable income is below a specified threshold. It effectively makes income up to the threshold <strong>tax-free</strong>.</p><h3>Section 87A Limits</h3><table><thead><tr><th>Regime</th><th>Income Threshold</th><th>Maximum Rebate</th></tr></thead><tbody><tr><td><strong>New Regime</strong></td><td>Up to ₹7,00,000</td><td>₹25,000</td></tr><tr><td><strong>Old Regime</strong></td><td>Up to ₹5,00,000</td><td>₹12,500</td></tr></tbody></table><h3>How It Works — Example</h3><p>Under the new regime, if your taxable income is ₹6,50,000:</p><ul><li>Tax on ₹6,50,000 = ₹22,500</li><li>Section 87A rebate = ₹22,500</li><li><strong>Net tax payable = ₹0</strong></li></ul><p>But if taxable income is ₹7,10,000, the full tax is payable (no rebate), resulting in a significant jump. This is why staying at or below ₹7L is highly beneficial.</p>`,
    faq: [
      { question: "What is the tax-free income limit under Section 87A?", answer: "Under the new regime, resident individuals with net taxable income up to ₹7 lakh pay zero income tax due to the 87A rebate. Under the old regime, the limit is ₹5 lakh. Note: this applies to taxable income after all deductions, not gross income." },
      { question: "Is Section 87A rebate available for NRIs?", answer: "No, Section 87A rebate is available only to resident individuals. Non-Resident Indians (NRIs) cannot claim this rebate regardless of their income level." },
      { question: "Does 87A rebate apply to capital gains tax?", answer: "The 87A rebate applies to income taxed at normal slab rates. For special rate incomes like STCG (20%) and LTCG (12.5%), the rebate treatment has specific rules and may not always apply depending on the type of income." }
    ]
  },
  "section-80e": {
    contentHTML: `<h3>What is Section 80E?</h3><p><strong>Section 80E</strong> provides a deduction for interest paid on an education loan taken for higher education. Unlike Section 80C, there is <strong>no upper limit</strong> on the deduction amount — the entire interest paid is deductible.</p><h3>Key Features</h3><table><thead><tr><th>Feature</th><th>Details</th></tr></thead><tbody><tr><td>Who can claim</td><td>Individual (for self, spouse, children, or student for whom you are legal guardian)</td></tr><tr><td>Maximum deduction</td><td>No limit — entire interest amount</td></tr><tr><td>Deduction period</td><td>8 years from the year interest repayment starts (or until interest is fully paid, whichever is earlier)</td></tr><tr><td>Loan must be from</td><td>Approved financial institution or charitable trust</td></tr><tr><td>Course eligibility</td><td>Any course after Senior Secondary (India or abroad)</td></tr></tbody></table><h3>Example</h3><p>If you pay ₹2,50,000 per year in education loan interest and are in the 30% tax bracket, you save ₹75,000 + cess in tax every year through Section 80E.</p>`,
    faq: [
      { question: "Is the principal repayment of education loan also deductible?", answer: "No, Section 80E covers only the INTEREST component of education loan repayment. However, the principal repayment may qualify under Section 80C if it falls within the ₹1.5 lakh limit and meets the conditions." },
      { question: "Can parents claim 80E deduction for a child's education loan?", answer: "Yes, if a parent takes an education loan for their child's higher education, the parent can claim the 80E deduction on the interest paid. The key requirement is that the loan must be in the parent's name." },
      { question: "Is Section 80E available under the new tax regime?", answer: "No, Section 80E deduction is NOT available under the new tax regime. To claim this benefit, you must opt for the old tax regime while filing your ITR." }
    ]
  },
  "depreciation": {
    contentHTML: `<h3>What is Depreciation?</h3><p><strong>Depreciation</strong> is the reduction in the value of an asset over time due to wear and tear, usage, or obsolescence. In the context of income tax, it represents a non-cash expense that reduces taxable business income.</p><h3>Depreciation Rates (Income Tax Act — WDV Method)</h3><table><thead><tr><th>Asset Class</th><th>Rate</th></tr></thead><tbody><tr><td>Buildings (general)</td><td>10%</td></tr><tr><td>Buildings (temporary)</td><td>40%</td></tr><tr><td>Furniture & Fittings</td><td>10%</td></tr><tr><td>Plant & Machinery (general)</td><td>15%</td></tr><tr><td>Motor Cars</td><td>15%</td></tr><tr><td>Computers & Software</td><td>40%</td></tr><tr><td>Intangible Assets</td><td>25%</td></tr></tbody></table><h3>Additional Depreciation</h3><p>Manufacturing businesses can claim <strong>additional depreciation of 20%</strong> on new plant and machinery in the year of acquisition (Section 32(1)(iia)), subject to conditions.</p>`,
    faq: [
      { question: "What is the difference between WDV and SLM depreciation?", answer: "Written Down Value (WDV) method charges higher depreciation in early years and is used for income tax purposes. Straight Line Method (SLM) charges equal depreciation each year and is used for company accounts under Companies Act. Both methods result in the same total depreciation over the asset's life." },
      { question: "Can an individual claim depreciation?", answer: "Yes, individuals can claim depreciation on assets used for business or profession. For example, a freelancer can claim depreciation on a laptop used for work. Assets used for personal purposes do not qualify." },
      { question: "Is depreciation a cash expense?", answer: "No, depreciation is a non-cash expense. It reduces taxable profit without any actual cash outflow in that year (the cash was spent when the asset was purchased). This makes it a valuable tax-saving tool for businesses." }
    ]
  },
  "gstin": {
    contentHTML: `<h3>What is GSTIN?</h3><p><strong>GSTIN (Goods and Services Tax Identification Number)</strong> is a unique 15-digit number assigned to every registered GST taxpayer. It is state-specific — a business operating in multiple states must obtain a separate GSTIN for each state.</p><h3>GSTIN Format</h3><p><strong>22AAAAA0000A1Z5</strong></p><table><thead><tr><th>Position</th><th>Digits</th><th>Meaning</th></tr></thead><tbody><tr><td>1-2</td><td>22</td><td>State code (e.g., 27 = Maharashtra, 06 = Haryana)</td></tr><tr><td>3-12</td><td>AAAAA0000A</td><td>PAN of the taxpayer</td></tr><tr><td>13</td><td>1</td><td>Entity number (for same PAN in same state)</td></tr><tr><td>14</td><td>Z</td><td>Default character</td></tr><tr><td>15</td><td>5</td><td>Check digit</td></tr></tbody></table><h3>When GSTIN Is Required</h3><ul><li>Mandatory on all GST invoices and bills</li><li>Required for filing GST returns</li><li>Needed for claiming Input Tax Credit</li><li>Must be displayed at the business premises</li></ul>`,
    faq: [
      { question: "How do I get a GSTIN?", answer: "Register on the GST portal (gst.gov.in) by providing PAN, Aadhaar, business details, and bank account information. GSTIN is allotted within 3-7 working days after successful verification. The process is entirely online and free of cost." },
      { question: "Can I have multiple GSTINs?", answer: "Yes, you need a separate GSTIN for each state where you have a place of business. You may also need separate GSTINs for different business verticals within the same state if you opt for the composition scheme for some verticals." },
      { question: "How do I verify a GSTIN?", answer: "Visit the GST portal (gst.gov.in), click on 'Search Taxpayer,' and enter the GSTIN. This will show the business name, registration status, type of registration, and whether the taxpayer is active. Always verify supplier GSTINs before accepting invoices for ITC claims." }
    ]
  },
  "hsn-code": {
    contentHTML: `<h3>What is an HSN Code?</h3><p><strong>HSN (Harmonized System of Nomenclature)</strong> is an internationally standardized system of names and numbers to classify traded products. In India, HSN codes are used in GST invoices to identify the applicable tax rate on goods.</p><h3>HSN Code Requirements Under GST</h3><table><thead><tr><th>Annual Turnover</th><th>HSN Digits Required</th></tr></thead><tbody><tr><td>Up to ₹5 crore</td><td>4-digit HSN on B2B invoices</td></tr><tr><td>Above ₹5 crore</td><td>6-digit HSN on all invoices</td></tr></tbody></table><h3>HSN Code Structure</h3><p><strong>Example: 6203.42.10</strong></p><ul><li><strong>62:</strong> Chapter (Articles of apparel — not knitted)</li><li><strong>6203:</strong> Heading (Men's suits, trousers)</li><li><strong>6203.42:</strong> Sub-heading (Trousers — cotton)</li><li><strong>6203.42.10:</strong> Tariff item (specific product)</li></ul>`,
    faq: [
      { question: "Where do I find the correct HSN code for my product?", answer: "You can search HSN codes on the GST portal (gst.gov.in) under the 'HSN Search' feature, or on the CBIC site. You can also use the Indian Customs tariff schedule. If uncertain, consult a CA or GST practitioner to avoid incorrect classification." },
      { question: "What happens if I use the wrong HSN code?", answer: "Using an incorrect HSN code can lead to incorrect GST rate application, rejection of Input Tax Credit claims by the buyer, and penalties during GST audits. It is important to classify products accurately." },
      { question: "Is HSN code mandatory on all GST invoices?", answer: "HSN codes are mandatory on B2B invoices for all registered taxpayers. For B2C invoices, they are required only if turnover exceeds ₹5 crore. Composition scheme dealers are exempt from mentioning HSN codes." }
    ]
  },
  "sac-code": {
    contentHTML: `<h3>What is a SAC Code?</h3><p><strong>SAC (Services Accounting Code)</strong> is a classification code used under GST to identify and categorize services. While HSN codes are used for goods, SAC codes serve the same purpose for services. SAC codes determine the applicable GST rate on a particular service.</p><h3>SAC Code Structure</h3><p><strong>Example: 998314</strong></p><ul><li><strong>99:</strong> All services start with 99</li><li><strong>9983:</strong> Group (Other professional, technical, and business services)</li><li><strong>998314:</strong> Specific service (Engineering services)</li></ul><h3>Common SAC Codes</h3><table><thead><tr><th>SAC Code</th><th>Service</th><th>GST Rate</th></tr></thead><tbody><tr><td>998313</td><td>Accounting & auditing</td><td>18%</td></tr><tr><td>998314</td><td>Engineering services</td><td>18%</td></tr><tr><td>997212</td><td>Renting of residential property</td><td>Exempt/18%</td></tr><tr><td>998511</td><td>Consulting services</td><td>18%</td></tr></tbody></table>`,
    faq: [
      { question: "Is SAC code mandatory on GST invoices for services?", answer: "Yes, service providers with turnover above ₹5 crore must mention SAC codes on all invoices. For turnover below ₹5 crore, 4-digit SAC codes are required on B2B invoices." },
      { question: "How do I find the correct SAC code for my service?", answer: "Search on the GST portal (gst.gov.in) or the CBIC website. The complete list of SAC codes with descriptions is available in the GST rate notification for services. If uncertain, consult a GST practitioner." },
      { question: "What is the difference between HSN and SAC codes?", answer: "HSN codes classify goods (products) and SAC codes classify services. HSN codes can be 4, 6, or 8 digits. SAC codes always start with '99' and are typically 6 digits. Both are used to determine the applicable GST rate." }
    ]
  },
  "e-way-bill": {
    contentHTML: `<h3>What is an E-way Bill?</h3><p>An <strong>E-way Bill</strong> is an electronic document required for the movement of goods worth more than ₹50,000. It is generated on the GST E-way Bill portal and must be carried by the transporter during goods movement.</p><h3>When E-way Bill Is Required</h3><table><thead><tr><th>Scenario</th><th>E-way Bill Required?</th></tr></thead><tbody><tr><td>Consignment value > ₹50,000 (inter-state)</td><td>Yes (mandatory)</td></tr><tr><td>Consignment value > ₹50,000 (intra-state)</td><td>Yes (varies by state threshold)</td></tr><tr><td>Goods sent for job work</td><td>Yes (even if value < ₹50,000)</td></tr><tr><td>Handicraft goods (inter-state)</td><td>Yes (even if < ₹50,000)</td></tr></tbody></table><h3>Validity of E-way Bill</h3><table><thead><tr><th>Distance</th><th>Validity</th></tr></thead><tbody><tr><td>Up to 200 km</td><td>1 day</td></tr><tr><td>Every additional 200 km</td><td>+1 day</td></tr><tr><td>Over-dimensional cargo</td><td>1 day per 20 km</td></tr></tbody></table>`,
    faq: [
      { question: "What happens if goods are transported without an E-way Bill?", answer: "Goods transported without a valid E-way Bill can be detained or seized. The penalty is ₹10,000 or the tax sought to be evaded, whichever is higher. The goods and vehicle can be released upon payment of the penalty and applicable tax." },
      { question: "Who is responsible for generating the E-way Bill?", answer: "The registered person (supplier) is primarily responsible. If the supplier does not generate it, the transporter can generate it. For imports, the importer or customs broker generates the E-way Bill." },
      { question: "Can I cancel an E-way Bill after generation?", answer: "Yes, an E-way Bill can be cancelled within 24 hours of generation, provided the goods have not been verified in transit by a tax officer. After 24 hours or verification, cancellation is not possible." }
    ]
  },
  "composition-scheme": {
    contentHTML: `<h3>What is the GST Composition Scheme?</h3><p>The <strong>Composition Scheme</strong> is a simplified GST compliance option for small businesses. Instead of filing detailed monthly returns, eligible businesses pay a fixed percentage of turnover as tax and file quarterly returns.</p><h3>Composition Scheme Rates</h3><table><thead><tr><th>Business Type</th><th>Composition Rate</th><th>Turnover Limit</th></tr></thead><tbody><tr><td>Manufacturers</td><td>1% (0.5% CGST + 0.5% SGST)</td><td>Up to ₹1.5 crore</td></tr><tr><td>Traders</td><td>1%</td><td>Up to ₹1.5 crore</td></tr><tr><td>Restaurants</td><td>5%</td><td>Up to ₹1.5 crore</td></tr><tr><td>Service Providers</td><td>6%</td><td>Up to ₹50 lakh</td></tr></tbody></table><h3>Key Restrictions</h3><ul><li>Cannot collect GST from customers (tax is borne by the dealer)</li><li>Cannot claim Input Tax Credit</li><li>Cannot make inter-state supply of goods</li><li>Cannot supply through e-commerce operators</li><li>Must mention "Composition Taxable Person" on every bill</li></ul>`,
    faq: [
      { question: "Who should opt for the Composition Scheme?", answer: "Small businesses with turnover up to ₹1.5 crore (₹50 lakh for service providers) that sell only within their state and have minimal input GST to claim. It significantly reduces compliance burden — quarterly returns instead of monthly, simpler calculations, and no detailed invoice matching." },
      { question: "Can a composition dealer sell on Amazon or Flipkart?", answer: "No, composition scheme dealers cannot supply goods through e-commerce operators. If you want to sell on e-commerce platforms, you must register as a regular GST taxpayer." },
      { question: "Can I claim ITC under the Composition Scheme?", answer: "No, composition scheme dealers cannot claim Input Tax Credit on purchases. This is a significant drawback if your purchases attract high GST rates. The tax saved on compliance may be offset by the loss of ITC." }
    ]
  },
  "financial-year": {
    contentHTML: `<h3>What is a Financial Year?</h3><p>A <strong>Financial Year (FY)</strong> in India runs from <strong>April 1 to March 31</strong> of the following calendar year. It is the period for which income is earned, expenses are incurred, and financial statements are prepared. The corresponding <strong>Assessment Year (AY)</strong> is the year in which tax returns for that FY are filed.</p><h3>FY vs. AY</h3><table><thead><tr><th>Concept</th><th>Period</th><th>Example</th></tr></thead><tbody><tr><td><strong>Financial Year</strong></td><td>April 1 – March 31</td><td>FY 2024-25 (Apr 2024 – Mar 2025)</td></tr><tr><td><strong>Assessment Year</strong></td><td>The year after FY</td><td>AY 2025-26 (Apr 2025 – Mar 2026)</td></tr></tbody></table><h3>Key Financial Year Dates</h3><ul><li><strong>April 1:</strong> New FY starts; choose tax regime (old/new)</li><li><strong>June 15:</strong> First advance tax instalment due</li><li><strong>July 31:</strong> ITR filing deadline (non-audit)</li><li><strong>October 31:</strong> ITR deadline for audit cases</li><li><strong>December 31:</strong> Belated/revised return deadline</li><li><strong>March 31:</strong> FY ends; last date for tax-saving investments under 80C</li></ul>`,
    faq: [
      { question: "Why does India's financial year start in April?", answer: "India follows the April-March financial year, inherited from British colonial practice. The original logic was to align with the harvest cycle — kharif crops are harvested in autumn and rabi crops in spring, making March an ideal point to assess agricultural income." },
      { question: "What is the difference between Financial Year and Assessment Year?", answer: "The Financial Year is when you earn income (FY 2024-25 = Apr 2024 to Mar 2025). The Assessment Year is when you file the tax return for that income (AY 2025-26 = Apr 2025 to Mar 2026). Simply put: AY = FY + 1." },
      { question: "When should I make tax-saving investments for the current FY?", answer: "Tax-saving investments (80C, 80D, NPS) must be made between April 1 and March 31 of the financial year. While most people invest in January-March (rush season), investing early via SIP gives you the benefit of compounding for a longer period." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' tax terms (batch 2)');
