const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "emi": {
    contentHTML: `<h3>What is EMI?</h3><p><strong>Equated Monthly Instalment (EMI)</strong> is the fixed amount a borrower pays to a lender on a specified date each month until the loan is fully repaid. Each EMI consists of two components: <strong>principal repayment</strong> and <strong>interest payment</strong>. In the early years, the interest component is larger; over time, the principal component grows.</p><h3>EMI Formula</h3><p><strong>EMI = P × r × (1+r)<sup>n</sup> / ((1+r)<sup>n</sup> − 1)</strong></p><table><thead><tr><th>Variable</th><th>Meaning</th><th>Example</th></tr></thead><tbody><tr><td><strong>P</strong></td><td>Principal loan amount</td><td>₹10,00,000</td></tr><tr><td><strong>r</strong></td><td>Monthly interest rate (annual rate ÷ 12 ÷ 100)</td><td>8.5% → 0.00708</td></tr><tr><td><strong>n</strong></td><td>Total number of monthly instalments</td><td>20 years → 240</td></tr></tbody></table><h3>EMI Breakdown Over Time</h3><table><thead><tr><th>Year</th><th>Interest Component</th><th>Principal Component</th></tr></thead><tbody><tr><td>Year 1</td><td>~70-80%</td><td>~20-30%</td></tr><tr><td>Year 10</td><td>~50%</td><td>~50%</td></tr><tr><td>Year 20</td><td>~10-15%</td><td>~85-90%</td></tr></tbody></table><h3>Tips to Reduce Your EMI</h3><ul><li>Make a larger <strong>down payment</strong> to reduce the principal</li><li>Opt for a <strong>longer tenure</strong> (increases total interest but lowers monthly outgo)</li><li>Negotiate a <strong>lower interest rate</strong> or do a balance transfer</li><li>Make <strong>part-prepayments</strong> whenever possible to reduce outstanding principal</li></ul>`,
    faq: [
      { question: "How is EMI calculated?", answer: "EMI is calculated using the formula: EMI = P × r × (1+r)^n / ((1+r)^n − 1), where P is the principal amount, r is the monthly interest rate, and n is the total number of instalments. Most banks use the reducing balance method for this calculation." },
      { question: "Does EMI include both principal and interest?", answer: "Yes, every EMI payment includes two components — a principal portion and an interest portion. In the initial months, the interest component is higher, but as you keep paying, the principal component gradually increases while the interest portion decreases." },
      { question: "Can I reduce my EMI after taking a loan?", answer: "Yes, you can reduce EMI by: (1) making part-prepayments to reduce outstanding principal, (2) transferring your loan to a bank offering lower interest rates, (3) requesting a tenure extension (this lowers EMI but increases total interest), or (4) negotiating with your lender during repo rate cuts." },
      { question: "What happens if I miss an EMI payment?", answer: "Missing an EMI results in a late payment fee (typically 1-2% of the EMI), a negative impact on your CIBIL/credit score, and potential legal action if defaults continue. Most banks provide a 2-3 day grace period before charging penalties." }
    ]
  },
  "principal": {
    contentHTML: `<h3>What is Principal?</h3><p><strong>Principal</strong> is the original amount of money borrowed from a lender or invested in a financial instrument, excluding any interest, fees, or earnings. In a loan context, it is the base amount on which interest is calculated. As you repay a loan, the outstanding principal decreases, which in turn reduces the interest charged each month under the reducing balance method.</p><h3>Principal vs. Interest</h3><table><thead><tr><th>Aspect</th><th>Principal</th><th>Interest</th></tr></thead><tbody><tr><td><strong>What it is</strong></td><td>Original borrowed amount</td><td>Cost of borrowing</td></tr><tr><td><strong>Changes over time?</strong></td><td>Decreases with each EMI</td><td>Decreases as principal reduces</td></tr><tr><td><strong>Tax benefit</strong></td><td>Sec 80C (up to ₹1.5L on home loan)</td><td>Sec 24(b) (up to ₹2L on home loan)</td></tr></tbody></table><h3>Example</h3><p>If you borrow ₹50,00,000 for a home loan at 8.5% for 20 years, your total repayment will be approximately ₹1,04,74,000 — of which ₹50,00,000 is principal and ₹54,74,000 is interest. Prepaying even ₹5,00,000 in the first 3 years can save over ₹8,00,000 in total interest.</p>`,
    faq: [
      { question: "What is the difference between principal and interest?", answer: "Principal is the original amount you borrowed, while interest is the cost the lender charges for lending you that money. In each EMI, you pay both — the principal portion reduces your loan balance, and the interest is the lender's profit." },
      { question: "How does principal reduction help save money?", answer: "When you reduce the outstanding principal (through prepayments), the interest is calculated on a smaller amount going forward. This reduces the total interest paid over the loan tenure and can either shorten your loan term or reduce your EMI amount." },
      { question: "Can I get tax benefits on principal repayment?", answer: "Yes, under Section 80C of the Income Tax Act, you can claim a deduction of up to ₹1,50,000 per year on the principal repayment of a home loan. This is available under the old tax regime." }
    ]
  },
  "interest-rate": {
    contentHTML: `<h3>What is Interest Rate?</h3><p>An <strong>interest rate</strong> is the percentage charged by a lender on the amount borrowed (principal), typically expressed as an annual percentage. It represents the cost of borrowing money and is the primary factor determining your EMI and total repayment amount.</p><h3>Types of Interest Rates in India</h3><table><thead><tr><th>Type</th><th>Description</th><th>Common Usage</th></tr></thead><tbody><tr><td><strong>Fixed Rate</strong></td><td>Stays constant throughout the loan tenure</td><td>Personal loans, car loans</td></tr><tr><td><strong>Floating Rate</strong></td><td>Changes with RBI repo rate / EBLR</td><td>Home loans, LAP</td></tr><tr><td><strong>Flat Rate</strong></td><td>Interest on original principal for full tenure</td><td>Some car/two-wheeler loans</td></tr><tr><td><strong>Reducing Balance</strong></td><td>Interest on outstanding principal only</td><td>Most bank loans</td></tr></tbody></table><h3>Current Benchmark Rates (India)</h3><table><thead><tr><th>Benchmark</th><th>Description</th></tr></thead><tbody><tr><td><strong>Repo Rate</strong></td><td>Rate at which RBI lends to banks (base for EBLR)</td></tr><tr><td><strong>MCLR</strong></td><td>Marginal Cost of Funds-based Lending Rate</td></tr><tr><td><strong>EBLR</strong></td><td>External Benchmark Lending Rate (repo rate + spread)</td></tr></tbody></table>`,
    faq: [
      { question: "What is the difference between flat rate and reducing balance rate?", answer: "A flat rate calculates interest on the original loan amount throughout the tenure, so you pay interest on money you've already repaid. A reducing balance rate calculates interest only on the outstanding principal, which decreases with each EMI. A 10% flat rate is roughly equivalent to an 18-19% reducing balance rate." },
      { question: "How does RBI repo rate affect my loan interest rate?", answer: "If your loan is linked to the repo rate (EBLR-based), a repo rate cut by RBI directly reduces your loan interest rate, lowering your EMI or shortening your tenure. Conversely, a repo rate hike increases your interest rate." },
      { question: "Which is better — fixed or floating interest rate?", answer: "Floating rates are generally lower than fixed rates and benefit borrowers when rates are declining. Fixed rates offer predictability. For long-tenure loans like home loans, floating rates are more common and usually more economical over time." }
    ]
  },
  "reducing-balance-method": {
    contentHTML: `<h3>What is the Reducing Balance Method?</h3><p>The <strong>reducing balance method</strong> (also called diminishing balance method) calculates interest only on the <strong>outstanding loan principal</strong> at the end of each period. As you pay EMIs and the principal decreases, the interest charged also reduces progressively. This is the standard method used by all Indian banks for home loans and most other secured loans.</p><h3>Reducing Balance vs. Flat Rate</h3><table><thead><tr><th>Feature</th><th>Reducing Balance</th><th>Flat Rate</th></tr></thead><tbody><tr><td>Interest calculated on</td><td>Outstanding principal</td><td>Original loan amount</td></tr><tr><td>Effective cost</td><td>Lower</td><td>Higher (nearly 1.8×)</td></tr><tr><td>EMI pattern</td><td>Fixed EMI, changing components</td><td>Fixed EMI, fixed components</td></tr><tr><td>Prepayment benefit</td><td>Significant savings</td><td>Limited savings</td></tr></tbody></table><h3>Example</h3><p>For a ₹10,00,000 loan at 10% for 5 years: <strong>Reducing balance</strong> total interest ≈ ₹2,74,000 vs. <strong>Flat rate</strong> total interest = ₹5,00,000. The reducing balance method saves ₹2,26,000.</p>`,
    faq: [
      { question: "Why is reducing balance method better for borrowers?", answer: "With the reducing balance method, you pay interest only on the remaining principal. As you repay the loan, your outstanding balance decreases, so each month you pay less interest and more principal. This results in significantly lower total interest compared to the flat rate method." },
      { question: "Do all banks in India use the reducing balance method?", answer: "Yes, RBI mandates that all banks use the reducing balance method for calculating interest on loans. However, some NBFCs and fintech lenders for small personal/vehicle loans may still quote flat rates, which appear lower but are effectively much higher." },
      { question: "How does prepayment work with the reducing balance method?", answer: "Prepayment directly reduces your outstanding principal. Since interest is calculated only on the remaining balance, even a small prepayment in the early years can save a substantial amount of interest over the loan tenure." }
    ]
  },
  "flat-rate": {
    contentHTML: `<h3>What is Flat Rate Interest?</h3><p>A <strong>flat rate</strong> is an interest calculation method where interest is computed on the <strong>original loan amount</strong> (not the reducing balance) for the entire tenure. This means you continue paying interest on money you have already repaid, making the effective interest rate significantly higher than the stated rate.</p><h3>Flat Rate to Effective Rate Conversion</h3><p><strong>Approximate formula:</strong> Effective Rate ≈ Flat Rate × 1.8 to 1.95</p><table><thead><tr><th>Stated Flat Rate</th><th>Approximate Effective Rate</th></tr></thead><tbody><tr><td>5%</td><td>~9–10%</td></tr><tr><td>8%</td><td>~14–16%</td></tr><tr><td>10%</td><td>~18–20%</td></tr><tr><td>12%</td><td>~22–24%</td></tr></tbody></table><h3>When Flat Rates Are Used</h3><ul><li>Two-wheeler loans from dealerships</li><li>Consumer durable finance (appliances, electronics)</li><li>Some NBFC personal loans</li><li>Gold loans from certain lenders</li></ul>`,
    faq: [
      { question: "Why do flat rates seem lower than reducing balance rates?", answer: "Flat rates appear lower because the stated percentage is smaller, but the total interest paid is much higher since you pay interest on the full original amount even as you repay principal. A 10% flat rate is roughly equivalent to an 18-20% reducing balance rate." },
      { question: "How do I compare a flat rate loan with a reducing balance loan?", answer: "Multiply the flat rate by approximately 1.8 to 1.95 to get the equivalent reducing balance rate. For example, a flat rate of 7% is comparable to a reducing balance rate of approximately 12.6% to 13.65%." },
      { question: "Is flat rate interest legal in India?", answer: "Yes, flat rate interest is legal and still used by some NBFCs and financing companies, especially for vehicle loans and consumer durable loans. However, RBI mandates that banks disclose both the flat rate and the effective annual rate so borrowers can make informed comparisons." }
    ]
  },
  "cibil-score": {
    contentHTML: `<h3>What is a CIBIL Score?</h3><p>A <strong>CIBIL Score</strong> is a three-digit numeric summary (ranging from 300 to 900) of your credit history, assigned by <strong>TransUnion CIBIL</strong>, India's oldest credit bureau. It reflects your creditworthiness based on past borrowing and repayment behavior. A score of 750+ is generally considered good for loan approvals.</p><h3>CIBIL Score Ranges</h3><table><thead><tr><th>Score Range</th><th>Rating</th><th>Loan Approval Chances</th><th>Interest Rate Impact</th></tr></thead><tbody><tr><td><strong>750–900</strong></td><td>Excellent</td><td>Very High</td><td>Lowest rates offered</td></tr><tr><td><strong>700–749</strong></td><td>Good</td><td>High</td><td>Competitive rates</td></tr><tr><td><strong>650–699</strong></td><td>Fair</td><td>Moderate</td><td>Higher rates, more scrutiny</td></tr><tr><td><strong>550–649</strong></td><td>Poor</td><td>Low</td><td>High rates or rejection</td></tr><tr><td><strong>300–549</strong></td><td>Very Poor</td><td>Very Low</td><td>Usually rejected</td></tr></tbody></table><h3>Factors Affecting CIBIL Score</h3><ul><li><strong>Payment history (35%):</strong> On-time EMI and credit card payments</li><li><strong>Credit utilization (30%):</strong> Keep below 30% of credit limit</li><li><strong>Credit age (15%):</strong> Longer credit history is better</li><li><strong>Credit mix (10%):</strong> Mix of secured and unsecured loans</li><li><strong>Recent inquiries (10%):</strong> Too many loan applications hurt your score</li></ul>`,
    faq: [
      { question: "What is a good CIBIL score for a home loan?", answer: "A CIBIL score of 750 or above is considered good for a home loan. With this score, you are likely to get faster approval and the lowest available interest rates. Scores between 700-749 are also acceptable but may attract slightly higher rates." },
      { question: "How can I improve my CIBIL score?", answer: "Pay all EMIs and credit card bills on time, keep credit utilization below 30%, avoid multiple loan applications in a short period, maintain a healthy mix of credit types, and regularly check your CIBIL report for errors that can be disputed." },
      { question: "How often is my CIBIL score updated?", answer: "CIBIL updates your score approximately every 30-45 days, based on information reported by lenders. Changes in your credit behavior (like paying off a loan or missing a payment) typically reflect in your score within 1-2 months." }
    ]
  },
  "ltv-ratio": {
    contentHTML: `<h3>What is LTV Ratio?</h3><p><strong>Loan-to-Value (LTV) ratio</strong> is the percentage of a property or asset's value that a bank is willing to finance. The remaining must be funded by the buyer as a <strong>down payment</strong>. RBI regulates maximum LTV ratios for home loans in India.</p><h3>RBI LTV Norms for Home Loans</h3><table><thead><tr><th>Property Value</th><th>Maximum LTV</th><th>Min Down Payment</th></tr></thead><tbody><tr><td>Up to ₹30 lakhs</td><td>90%</td><td>10%</td></tr><tr><td>₹30 lakhs – ₹75 lakhs</td><td>80%</td><td>20%</td></tr><tr><td>Above ₹75 lakhs</td><td>75%</td><td>25%</td></tr></tbody></table><h3>Why LTV Matters</h3><ul><li><strong>Lower LTV = lower risk</strong> for the bank → better interest rates for you</li><li><strong>Higher LTV = less down payment</strong> needed but higher EMI and total interest</li><li>LTV above 80% may require <strong>mortgage insurance</strong> in some cases</li></ul>`,
    faq: [
      { question: "What is the maximum LTV ratio for home loans in India?", answer: "As per RBI guidelines, the maximum LTV ratio is 90% for properties valued up to ₹30 lakhs, 80% for properties between ₹30-75 lakhs, and 75% for properties above ₹75 lakhs. This means you need a minimum down payment of 10-25% depending on the property value." },
      { question: "Does a lower LTV ratio get me a better interest rate?", answer: "Yes, a lower LTV ratio indicates that you are contributing more of your own funds, which reduces the lender's risk. Many banks offer a 0.05-0.10% interest rate reduction for LTV ratios below 70%." },
      { question: "How is LTV ratio calculated?", answer: "LTV Ratio = (Loan Amount ÷ Property Value) × 100. For example, if the property costs ₹1 crore and the bank sanctions ₹75 lakhs, the LTV ratio is 75%." }
    ]
  },
  "down-payment": {
    contentHTML: `<h3>What is a Down Payment?</h3><p>A <strong>down payment</strong> is the initial upfront portion of the purchase price that the buyer pays from their own funds when purchasing an asset (typically a home or vehicle). The remaining amount is financed through a loan. A larger down payment reduces the loan amount, EMI, and total interest paid.</p><h3>Typical Down Payments in India</h3><table><thead><tr><th>Loan Type</th><th>Typical Down Payment</th><th>Minimum Required</th></tr></thead><tbody><tr><td><strong>Home Loan</strong></td><td>10–25%</td><td>10% (for ≤₹30L property)</td></tr><tr><td><strong>Car Loan</strong></td><td>10–20%</td><td>10–15%</td></tr><tr><td><strong>Two-Wheeler Loan</strong></td><td>10–30%</td><td>10%</td></tr></tbody></table><h3>Benefits of a Larger Down Payment</h3><ul><li>Lower loan amount → <strong>lower EMI</strong></li><li>Lower LTV ratio → <strong>better interest rate</strong></li><li>Less total interest over the loan tenure</li><li>Faster loan approval with less documentation scrutiny</li></ul>`,
    faq: [
      { question: "What is the minimum down payment for a home loan in India?", answer: "The minimum down payment depends on the property value: 10% for properties up to ₹30 lakhs, 20% for ₹30-75 lakhs, and 25% for properties above ₹75 lakhs, as per RBI's LTV norms." },
      { question: "Should I pay a larger down payment or invest the money?", answer: "If your loan interest rate is higher than your expected investment returns, paying a larger down payment makes financial sense. For example, if your home loan rate is 8.5% and your investments earn 10-12% post-tax, investing may be better — but loan interest savings are guaranteed while investment returns are not." },
      { question: "Can I use a personal loan for a down payment?", answer: "Banks typically do not allow this, and some may ask for 3-6 months of bank statements to verify that the down payment comes from legitimate savings. Using a personal loan for a down payment increases your debt burden and may reduce your home loan eligibility." }
    ]
  },
  "prepayment": {
    contentHTML: `<h3>What is Loan Prepayment?</h3><p><strong>Prepayment</strong> means paying part of your outstanding loan before the scheduled EMI dates. This reduces the principal balance, which in turn either shortens the loan tenure or reduces the EMI amount. Prepayment is one of the most effective ways to save on interest costs.</p><h3>Prepayment Rules in India</h3><table><thead><tr><th>Loan Type</th><th>Floating Rate</th><th>Fixed Rate</th></tr></thead><tbody><tr><td><strong>Home Loan</strong></td><td>No prepayment charges (RBI rule)</td><td>Up to 2-3% of prepaid amount</td></tr><tr><td><strong>Personal Loan</strong></td><td>0-4% (varies by lender)</td><td>2-5% typically</td></tr><tr><td><strong>Car Loan</strong></td><td>Usually no charges after 6-12 months</td><td>1-2% of prepaid amount</td></tr></tbody></table><h3>Prepayment Strategy</h3><ul><li><strong>Best time to prepay:</strong> In the first 1/3rd of the loan tenure (when interest component is highest)</li><li><strong>Minimum amount:</strong> Most banks require prepayment to be at least 2-3 EMIs</li><li><strong>Frequency:</strong> Many banks allow 1-2 prepayments per year</li></ul>`,
    faq: [
      { question: "Is there a penalty for prepaying a home loan in India?", answer: "For floating rate home loans, RBI has mandated that banks cannot charge any prepayment penalty. For fixed rate home loans, banks may charge up to 2-3% of the prepaid amount as a penalty." },
      { question: "Should I reduce EMI or tenure after prepayment?", answer: "Reducing tenure is more beneficial financially as it saves more total interest. However, if you need cash flow flexibility, reducing the EMI amount may be more practical. For maximum savings, choose tenure reduction." },
      { question: "When is the best time to prepay a loan?", answer: "The earlier the better. In the first few years of a loan, the interest component in each EMI is much higher than the principal component. Prepaying early dramatically reduces the total interest paid over the loan's lifetime." }
    ]
  },
  "foreclosure": {
    contentHTML: `<h3>What is Loan Foreclosure?</h3><p><strong>Foreclosure</strong> (also called full prepayment or premature closure) means closing a loan entirely before the scheduled tenure ends by paying off the complete outstanding principal in one lump sum. This is different from part-prepayment, where you pay only a portion of the outstanding balance.</p><h3>Foreclosure Charges</h3><table><thead><tr><th>Loan Type</th><th>Floating Rate</th><th>Fixed Rate</th></tr></thead><tbody><tr><td><strong>Home Loan (individual)</strong></td><td>NIL (RBI mandated)</td><td>Up to 2-4%</td></tr><tr><td><strong>Personal Loan</strong></td><td>1-5% (lock-in period applies)</td><td>2-5%</td></tr><tr><td><strong>Business Loan</strong></td><td>2-4%</td><td>3-5%</td></tr></tbody></table><h3>When Should You Foreclose?</h3><ul><li>When you have surplus funds from bonus, inheritance, or asset sale</li><li>When you are in the <strong>first half</strong> of loan tenure (maximum interest savings)</li><li>When foreclosure charges are lower than the remaining interest to be paid</li></ul>`,
    faq: [
      { question: "What is the difference between foreclosure and prepayment?", answer: "Foreclosure means closing the entire loan by paying off all outstanding dues in one shot. Prepayment (part-prepayment) means paying a portion of the outstanding principal while the loan continues with revised EMI or tenure." },
      { question: "Can a bank refuse loan foreclosure?", answer: "No, a bank cannot refuse foreclosure. As per RBI guidelines, borrowers have the right to foreclose their loans. For floating rate home loans taken by individual borrowers, banks cannot charge any foreclosure fee." },
      { question: "How do I calculate if foreclosure is worth it?", answer: "Compare the foreclosure charges (if any) against the total remaining interest you would pay if you continued the loan. If the remaining interest is significantly more than the foreclosure penalty, it's financially beneficial to foreclose." }
    ]
  },
  "moratorium-period": {
    contentHTML: `<h3>What is a Moratorium Period?</h3><p>A <strong>moratorium period</strong> is a grace period during which the borrower is not required to make any loan repayments (EMIs). It is commonly offered on education loans, home loans for under-construction properties, and was notably extended to all borrowers during the COVID-19 pandemic by RBI.</p><h3>Common Moratorium Scenarios</h3><table><thead><tr><th>Loan Type</th><th>Moratorium Period</th><th>Details</th></tr></thead><tbody><tr><td><strong>Education Loan</strong></td><td>Course duration + 6-12 months</td><td>No EMI during study period</td></tr><tr><td><strong>Home Loan (under construction)</strong></td><td>Until possession</td><td>Only pre-EMI interest charged</td></tr><tr><td><strong>COVID-19 RBI moratorium</strong></td><td>6 months (Mar-Aug 2020)</td><td>Optional deferral of all EMIs</td></tr></tbody></table><h3>Important Note</h3><p>During a moratorium, <strong>interest continues to accrue</strong> on the outstanding principal. This accrued interest is either added to the principal (increasing it) or needs to be paid separately. A moratorium is a pause in payments, not a waiver.</p>`,
    faq: [
      { question: "Does interest accumulate during a moratorium period?", answer: "Yes, interest continues to accrue on the outstanding loan amount during the moratorium period. This accumulated interest may be added to the principal (compounded), increasing your total repayment. A moratorium is a payment deferral, not an interest waiver." },
      { question: "Is a moratorium period the same as a grace period?", answer: "They are similar but not identical. A moratorium is a structured period granted at the start of a loan where no payments are required. A grace period is typically a short window (a few days) after an EMI due date before a late fee is charged." },
      { question: "Should I opt for a moratorium if offered?", answer: "Only if you genuinely need cash flow relief. Opting for a moratorium increases your total interest cost because interest keeps accruing. If you can afford to pay EMIs, it is financially better to continue paying rather than opt for a moratorium." }
    ]
  },
  "processing-fee": {
    contentHTML: `<h3>What is a Loan Processing Fee?</h3><p>A <strong>processing fee</strong> is a one-time, non-refundable charge levied by the lender for processing your loan application. It covers administrative costs like KYC verification, credit checks, property valuation, and documentation. This fee is typically deducted from the loan disbursement amount.</p><h3>Typical Processing Fees in India</h3><table><thead><tr><th>Loan Type</th><th>Processing Fee</th><th>Typical Range</th></tr></thead><tbody><tr><td><strong>Home Loan</strong></td><td>0.25% – 1% of loan amount</td><td>₹3,000 – ₹50,000</td></tr><tr><td><strong>Personal Loan</strong></td><td>1% – 3% of loan amount</td><td>₹1,000 – ₹25,000</td></tr><tr><td><strong>Car Loan</strong></td><td>0.5% – 1%</td><td>₹2,000 – ₹10,000</td></tr><tr><td><strong>Education Loan</strong></td><td>0 – 1%</td><td>NIL – ₹10,000</td></tr></tbody></table><h3>Tips</h3><ul><li>Processing fees are often <strong>negotiable</strong> — ask for a waiver or reduction</li><li>Many banks offer <strong>zero processing fee</strong> during festive seasons</li><li>Compare the effective cost (interest rate + fees) across lenders, not just the headline rate</li></ul>`,
    faq: [
      { question: "Is the processing fee refundable if my loan is rejected?", answer: "In most cases, the processing fee is non-refundable regardless of whether your loan is approved or rejected. Some banks may refund a portion if the rejection is on their end, but this varies by lender. Always confirm the refund policy before paying." },
      { question: "Can I negotiate the processing fee?", answer: "Yes, processing fees are often negotiable. If you have a good credit score (750+), an existing relationship with the bank, or are applying during festive season offers, you can request a fee waiver or reduction. Bank employees often have the authority to waive fees to close deals." },
      { question: "Is processing fee the only charge when taking a loan?", answer: "No. Other charges may include documentation charges, administrative fees, prepayment/foreclosure charges, insurance premiums, and stamp duty. Always ask for a complete list of all fees and charges before signing the loan agreement." }
    ]
  },
  "repo-rate": {
    contentHTML: `<h3>What is the Repo Rate?</h3><p>The <strong>Repo Rate</strong> (Repurchase Rate) is the rate at which the Reserve Bank of India (RBI) lends short-term funds to commercial banks against government securities. It is the primary monetary policy tool used by RBI to control inflation and economic growth. When RBI changes the repo rate, it directly affects lending rates across the banking system.</p><h3>How Repo Rate Affects You</h3><table><thead><tr><th>RBI Action</th><th>Effect on Banks</th><th>Effect on Borrowers</th></tr></thead><tbody><tr><td><strong>Repo Rate Cut</strong></td><td>Banks' borrowing cost decreases</td><td>Loan interest rates decrease, EMIs reduce</td></tr><tr><td><strong>Repo Rate Hike</strong></td><td>Banks' borrowing cost increases</td><td>Loan interest rates increase, EMIs rise</td></tr></tbody></table><h3>Repo Rate vs. Other Rates</h3><table><thead><tr><th>Rate</th><th>Description</th><th>Relationship</th></tr></thead><tbody><tr><td><strong>Repo Rate</strong></td><td>RBI lends to banks</td><td>Base rate for EBLR</td></tr><tr><td><strong>Reverse Repo Rate</strong></td><td>Banks park money with RBI</td><td>Always lower than repo</td></tr><tr><td><strong>EBLR</strong></td><td>Bank lending rate = Repo + spread</td><td>Directly linked to repo</td></tr><tr><td><strong>MCLR</strong></td><td>Internal cost-based bank rate</td><td>Indirectly linked</td></tr></tbody></table>`,
    faq: [
      { question: "How does a repo rate cut benefit home loan borrowers?", answer: "Since October 2019, new home loans are linked to the repo rate via EBLR (External Benchmark Lending Rate). When RBI cuts the repo rate, banks must pass the reduction to borrowers, lowering your loan interest rate and either reducing your EMI or shortening your tenure." },
      { question: "What is the current repo rate in India?", answer: "The repo rate is set by the RBI Monetary Policy Committee (MPC) which meets bi-monthly. You can check the current rate on the RBI website. Repo rate changes are immediately transmitted to EBLR-linked loans." },
      { question: "What is the difference between repo rate and MCLR?", answer: "Repo rate is set by RBI and is external to banks. MCLR (Marginal Cost of Funds-based Lending Rate) is an internal benchmark set by each bank based on its own cost of funds. EBLR-linked loans (linked to repo rate) transmit rate changes faster than MCLR-linked loans." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' loan terms (batch 1)');
