const fs = require('fs');
const data = JSON.parse(fs.readFileSync('./data/glossary.json', 'utf8'));

const enrichments = {
  "income-tax": {
    contentHTML: `<h3>What is Income Tax?</h3><p><strong>Income Tax</strong> is a direct tax levied by the Government of India on the income earned by individuals, HUFs, firms, and companies during a financial year (April–March). It is governed by the <strong>Income Tax Act, 1961</strong> and administered by the CBDT.</p><h3>Income Tax Slabs — New Regime (FY 2024-25)</h3><table><thead><tr><th>Income Range</th><th>Tax Rate</th></tr></thead><tbody><tr><td>Up to ₹3,00,000</td><td>Nil</td></tr><tr><td>₹3,00,001 – ₹7,00,000</td><td>5%</td></tr><tr><td>₹7,00,001 – ₹10,00,000</td><td>10%</td></tr><tr><td>₹10,00,001 – ₹12,00,000</td><td>15%</td></tr><tr><td>₹12,00,001 – ₹15,00,000</td><td>20%</td></tr><tr><td>Above ₹15,00,000</td><td>30%</td></tr></tbody></table><h3>Old vs. New Tax Regime</h3><table><thead><tr><th>Feature</th><th>Old Regime</th><th>New Regime</th></tr></thead><tbody><tr><td>Deductions (80C, 80D, etc.)</td><td>Available</td><td>Not available</td></tr><tr><td>Standard Deduction</td><td>₹50,000</td><td>₹75,000</td></tr><tr><td>Tax rates</td><td>Higher</td><td>Lower</td></tr><tr><td>Best for</td><td>Those with heavy deductions</td><td>Those with few deductions</td></tr></tbody></table>`,
    faq: [
      { question: "Which tax regime should I choose — old or new?", answer: "If your total deductions (80C + 80D + HRA + 24b + others) exceed ₹3-4 lakh, the old regime may save more tax. If your deductions are below ₹2-3 lakh, the new regime with lower rates is likely better. Use an income tax calculator to compare both regimes." },
      { question: "What is the tax-free income limit in India?", answer: "Under the new regime (FY 2024-25), income up to ₹3 lakh is tax-free. With the Section 87A rebate, individuals with net taxable income up to ₹7 lakh pay zero tax. Under the old regime, the basic exemption limit is ₹2.5 lakh (₹3 lakh for senior citizens)." },
      { question: "When do I need to file my income tax return?", answer: "Salaried individuals and non-audit cases must file ITR by July 31 of the assessment year. For example, for income earned in FY 2024-25 (April 2024–March 2025), the due date is July 31, 2025." }
    ]
  },
  "section-80c": {
    contentHTML: `<h3>What is Section 80C?</h3><p><strong>Section 80C</strong> of the Income Tax Act allows deductions of up to <strong>₹1,50,000</strong> per financial year from your gross taxable income. It is the most widely used tax-saving section and covers a broad range of investments and expenses.</p><h3>Eligible Investments Under 80C</h3><table><thead><tr><th>Investment</th><th>Lock-in</th><th>Returns</th><th>Risk</th></tr></thead><tbody><tr><td><strong>ELSS Mutual Funds</strong></td><td>3 years</td><td>10-15%</td><td>Market-linked</td></tr><tr><td><strong>PPF</strong></td><td>15 years</td><td>7.1%</td><td>Zero</td></tr><tr><td><strong>EPF (Employee PF)</strong></td><td>Until retirement</td><td>8.25%</td><td>Zero</td></tr><tr><td><strong>NSC</strong></td><td>5 years</td><td>7.7%</td><td>Zero</td></tr><tr><td><strong>Tax-Saving FD</strong></td><td>5 years</td><td>6.5-7%</td><td>Very Low</td></tr><tr><td><strong>SCSS</strong></td><td>5 years</td><td>8.2%</td><td>Zero</td></tr><tr><td><strong>Life Insurance Premium</strong></td><td>Varies</td><td>4-6%</td><td>Low</td></tr><tr><td><strong>Home Loan Principal</strong></td><td>—</td><td>Savings on interest</td><td>—</td></tr><tr><td><strong>Children's Tuition Fees</strong></td><td>—</td><td>—</td><td>—</td></tr><tr><td><strong>Stamp Duty</strong></td><td>—</td><td>—</td><td>—</td></tr></tbody></table>`,
    faq: [
      { question: "Is Section 80C available under the new tax regime?", answer: "No, Section 80C deductions are NOT available under the new tax regime (introduced in Budget 2020). If you want to claim 80C benefits, you must choose the old tax regime while filing your ITR." },
      { question: "What is the maximum deduction under Section 80C?", answer: "The maximum deduction under Section 80C is ₹1,50,000 per financial year. This limit includes the combined total of all eligible investments (ELSS, PPF, EPF, NSC, tax-saving FD, insurance premiums, tuition fees, etc.)." },
      { question: "Does EPF contribution count under 80C?", answer: "Yes, the employee's contribution to EPF (12% of basic salary) is automatically eligible for Section 80C deduction up to ₹1.5 lakh. The employer's contribution is not taxable (up to ₹7.5 lakh) and does not count under 80C." }
    ]
  },
  "section-80d": {
    contentHTML: `<h3>What is Section 80D?</h3><p><strong>Section 80D</strong> provides tax deduction for health insurance premiums paid and preventive health check-up expenses. This is in addition to the ₹1.5 lakh limit under Section 80C.</p><h3>Deduction Limits Under 80D</h3><table><thead><tr><th>Insured Person</th><th>Self/Family (below 60)</th><th>Parents (below 60)</th><th>Parents (60+)</th></tr></thead><tbody><tr><td><strong>Health Insurance Premium</strong></td><td>Up to ₹25,000</td><td>Up to ₹25,000</td><td>Up to ₹50,000</td></tr><tr><td><strong>Preventive Health Check-up</strong></td><td>₹5,000 (within above limit)</td><td>₹5,000 (within above limit)</td><td>₹5,000 (within above limit)</td></tr></tbody></table><h3>Maximum Possible Deduction</h3><ul><li><strong>Both below 60:</strong> ₹25,000 (self) + ₹25,000 (parents) = ₹50,000</li><li><strong>Parents 60+:</strong> ₹25,000 + ₹50,000 = ₹75,000</li><li><strong>All 60+:</strong> ₹50,000 + ₹50,000 = ₹1,00,000</li></ul>`,
    faq: [
      { question: "Is Section 80D available under the new tax regime?", answer: "No, Section 80D deductions for health insurance premiums are NOT available under the new tax regime. To claim 80D benefits, you must opt for the old tax regime." },
      { question: "Can I claim 80D for health insurance paid for parents?", answer: "Yes, you can claim a separate deduction of up to ₹25,000 (₹50,000 if parents are senior citizens aged 60+) for health insurance premiums paid for your parents. This is over and above the deduction for your own family's insurance." },
      { question: "Does corporate health insurance count under 80D?", answer: "No, the premium paid by your employer for group health insurance does not qualify for 80D deduction since the employee is not paying it. Only premiums you pay from your own pocket qualify for the deduction." }
    ]
  },
  "section-24b": {
    contentHTML: `<h3>What is Section 24(b)?</h3><p><strong>Section 24(b)</strong> allows a deduction of up to <strong>₹2,00,000</strong> per year on the interest paid on a home loan for a self-occupied property. This is one of the largest single deductions available to homeowners.</p><h3>Deduction Limits</h3><table><thead><tr><th>Property Type</th><th>Maximum Deduction</th><th>Condition</th></tr></thead><tbody><tr><td><strong>Self-Occupied</strong></td><td>₹2,00,000/year</td><td>Construction completed within 5 years</td></tr><tr><td><strong>Let-Out (Rented)</strong></td><td>No upper limit</td><td>Entire interest deductible against rental income</td></tr><tr><td><strong>Under Construction</strong></td><td>Pre-EMI interest deductible in 5 equal instalments after possession</td><td>Within overall ₹2L limit</td></tr></tbody></table><h3>Combined Tax Benefit on Home Loan</h3><ul><li><strong>Section 24(b):</strong> Up to ₹2,00,000 on interest (old regime)</li><li><strong>Section 80C:</strong> Up to ₹1,50,000 on principal repayment (old regime)</li><li><strong>Section 80EEA:</strong> Additional ₹1,50,000 for first-time buyers (if applicable)</li></ul>`,
    faq: [
      { question: "Can I claim Section 24(b) under the new tax regime?", answer: "For self-occupied property: No, Section 24(b) deduction is NOT available under the new tax regime. For let-out property: Yes, the interest deduction against rental income is available even under the new regime (but limited to the extent of rental income in the new regime)." },
      { question: "What if my home loan interest exceeds ₹2 lakh?", answer: "For self-occupied property, any interest above ₹2 lakh cannot be claimed or carried forward. For let-out property, the entire interest is deductible without limit, and if there is a loss, up to ₹2 lakh can be set off against other income." },
      { question: "Can both husband and wife claim Section 24(b)?", answer: "Yes, if both are co-borrowers and co-owners of the property, each can independently claim up to ₹2 lakh deduction on home loan interest under Section 24(b), effectively allowing up to ₹4 lakh combined deduction for the family." }
    ]
  },
  "hra": {
    contentHTML: `<h3>What is HRA?</h3><p><strong>House Rent Allowance (HRA)</strong> is a salary component provided by employers to help employees meet rental housing expenses. HRA is partially or fully exempt from income tax under Section 10(13A), making it one of the most valuable tax-saving tools for salaried individuals.</p><h3>HRA Exemption Calculation</h3><p>The HRA exemption is the <strong>minimum</strong> of:</p><table><thead><tr><th>Condition</th><th>Formula</th></tr></thead><tbody><tr><td>Actual HRA received</td><td>As per salary slip</td></tr><tr><td>Rent paid minus 10% of basic salary</td><td>Rent paid − (10% × Basic)</td></tr><tr><td>50% or 40% of basic salary</td><td>50% (metro) or 40% (non-metro) of Basic</td></tr></tbody></table><h3>Example</h3><p>Basic: ₹6,00,000 | HRA: ₹3,00,000 | Rent: ₹20,000/month (₹2,40,000/year) | City: Delhi (metro)</p><ul><li>Actual HRA: ₹3,00,000</li><li>Rent − 10% of Basic: ₹2,40,000 − ₹60,000 = ₹1,80,000</li><li>50% of Basic: ₹3,00,000</li><li><strong>Exempt HRA = ₹1,80,000</strong> (minimum of the three)</li></ul>`,
    faq: [
      { question: "Can I claim HRA exemption under the new tax regime?", answer: "No, HRA exemption under Section 10(13A) is NOT available under the new tax regime. If you pay significant rent, the old regime may save you more tax due to HRA benefits." },
      { question: "Can I claim both HRA and home loan benefits?", answer: "Yes, you can claim HRA exemption and home loan benefits simultaneously. This is common when you own a house in one city (on loan) but live and work in another city (on rent). The conditions are: you must actually pay rent, and the rented house and owned house must be in different cities." },
      { question: "Do I need rent receipts to claim HRA?", answer: "Yes, rent receipts are required if annual rent exceeds ₹1,00,000. You also need the landlord's PAN if annual rent exceeds ₹1,00,000. Without receipts, the employer may not provide HRA exemption in Form 16." }
    ]
  },
  "tds": {
    contentHTML: `<h3>What is TDS?</h3><p><strong>Tax Deducted at Source (TDS)</strong> is a system where tax is collected at the source of income itself. The payer (employer, bank, client) deducts tax before making payment and deposits it with the government on your behalf.</p><h3>Common TDS Rates</h3><table><thead><tr><th>Income Type</th><th>Section</th><th>TDS Rate</th><th>Threshold</th></tr></thead><tbody><tr><td>Salary</td><td>192</td><td>As per slab</td><td>Basic exemption limit</td></tr><tr><td>FD Interest</td><td>194A</td><td>10%</td><td>₹40,000/year (₹50,000 seniors)</td></tr><tr><td>Rent (>₹50K/month)</td><td>194-IB</td><td>5%</td><td>₹50,000/month</td></tr><tr><td>Professional Fees</td><td>194J</td><td>10%</td><td>₹30,000/year</td></tr><tr><td>Property Sale</td><td>194-IA</td><td>1%</td><td>₹50,00,000</td></tr></tbody></table><h3>What to Do If Excess TDS Is Deducted</h3><ul><li>File your <strong>Income Tax Return (ITR)</strong></li><li>Claim refund for excess TDS deducted</li><li>Submit <strong>Form 15G/15H</strong> to avoid TDS if income is below taxable limit</li></ul>`,
    faq: [
      { question: "How do I check TDS deducted on my income?", answer: "Log in to the Income Tax e-filing portal (incometax.gov.in) and view your Form 26AS or Annual Information Statement (AIS). These show all TDS deducted by various payers against your PAN during the financial year." },
      { question: "What is Form 15G and when should I submit it?", answer: "Form 15G is a self-declaration submitted to banks/payers to avoid TDS deduction when your total income is below the taxable limit. Senior citizens use Form 15H. Submit at the start of each financial year to the bank where you have FDs." },
      { question: "What happens if TDS is deducted but not deposited by the deductor?", answer: "Even if the deductor fails to deposit TDS with the government, you can still claim credit for it in your ITR, provided you can show it was deducted (via pay slips, bank statements). The government will pursue the deductor for the unpaid amount." }
    ]
  },
  "gst": {
    contentHTML: `<h3>What is GST?</h3><p><strong>Goods and Services Tax (GST)</strong> is a comprehensive, multi-stage, destination-based indirect tax levied on the supply of goods and services in India. Introduced on <strong>July 1, 2017</strong>, it replaced multiple indirect taxes (VAT, Service Tax, Excise Duty, etc.) with a single unified tax.</p><h3>GST Rate Structure</h3><table><thead><tr><th>Rate</th><th>Examples</th></tr></thead><tbody><tr><td><strong>0% (Exempt)</strong></td><td>Fresh food, healthcare, education</td></tr><tr><td><strong>5%</strong></td><td>Packaged food, economy hotel rooms, rail tickets</td></tr><tr><td><strong>12%</strong></td><td>Processed food, business class air tickets, apparel ₹1000+</td></tr><tr><td><strong>18%</strong></td><td>Most services, IT, telecom, restaurant (AC), stationery</td></tr><tr><td><strong>28%</strong></td><td>Luxury cars, aerated drinks, tobacco, cement, white goods</td></tr></tbody></table><h3>Types of GST</h3><table><thead><tr><th>Type</th><th>When Applied</th><th>Collected By</th></tr></thead><tbody><tr><td><strong>CGST</strong></td><td>Intra-state supply</td><td>Central Government</td></tr><tr><td><strong>SGST</strong></td><td>Intra-state supply</td><td>State Government</td></tr><tr><td><strong>IGST</strong></td><td>Inter-state supply</td><td>Central Government</td></tr></tbody></table>`,
    faq: [
      { question: "When do I need to register for GST?", answer: "GST registration is mandatory if your annual turnover exceeds ₹40 lakhs for goods (₹20 lakhs for services, ₹10 lakhs for special category states). It is also mandatory for inter-state suppliers, e-commerce operators, and casual taxable persons regardless of turnover." },
      { question: "How often do I need to file GST returns?", answer: "Regular taxpayers file GSTR-3B (summary return) monthly by the 20th, and GSTR-1 (outward supply details) monthly or quarterly depending on turnover. Composition scheme dealers file quarterly returns. Annual return GSTR-9 is due by December 31." },
      { question: "What is the difference between CGST, SGST, and IGST?", answer: "For intra-state sales (within the same state), GST is split equally into CGST (Central) and SGST (State). For inter-state sales, IGST (Integrated) is charged at the full rate. The total tax amount is the same — only the collection mechanism differs." }
    ]
  },
  "cgst": {
    contentHTML: `<h3>What is CGST?</h3><p><strong>Central Goods and Services Tax (CGST)</strong> is the portion of GST collected by the Central Government on intra-state (within the same state) supply of goods and services. CGST is always charged alongside <strong>SGST</strong> in equal proportions.</p><h3>How CGST Works</h3><table><thead><tr><th>Transaction Type</th><th>Tax Applied</th><th>Example (18% GST)</th></tr></thead><tbody><tr><td>Within same state</td><td>CGST (9%) + SGST (9%)</td><td>₹1,000 + ₹90 CGST + ₹90 SGST = ₹1,180</td></tr><tr><td>Between states</td><td>IGST (18%)</td><td>₹1,000 + ₹180 IGST = ₹1,180</td></tr></tbody></table><p>The total tax is the same (18%), but the division between central and state governments changes based on whether the transaction is intra-state or inter-state.</p>`,
    faq: [
      { question: "Can I use CGST input credit against SGST liability?", answer: "No, CGST credit can only be used against CGST or IGST liability. It cannot be used to offset SGST. Similarly, SGST credit can only be used against SGST or IGST. This cross-utilization restriction is to protect state revenue." },
      { question: "Is CGST rate always equal to SGST rate?", answer: "Yes, for any intra-state transaction, CGST and SGST are always equal. If the GST rate on a product is 18%, it will be split as 9% CGST + 9% SGST. If 12%, then 6% CGST + 6% SGST." },
      { question: "Where does CGST revenue go?", answer: "CGST revenue goes entirely to the Central Government's Consolidated Fund of India. It forms a significant part of the central government's indirect tax revenue and is used for national-level programs and expenditure." }
    ]
  },
  "sgst": {
    contentHTML: `<h3>What is SGST?</h3><p><strong>State Goods and Services Tax (SGST)</strong> is the portion of GST collected by the State Government on intra-state supplies. It is charged at the same rate as CGST and replaces the earlier state-level taxes like VAT, Entry Tax, and Entertainment Tax.</p><h3>SGST Collection Flow</h3><ul><li>SGST is collected by the seller and deposited with the <strong>state government</strong> where the supply originates</li><li>Revenue goes to the respective state's Consolidated Fund</li><li>Used for state-level infrastructure, welfare, and development programs</li></ul><h3>SGST vs. UTGST</h3><table><thead><tr><th>Tax</th><th>Applicable In</th></tr></thead><tbody><tr><td><strong>SGST</strong></td><td>All states (29 + 2 with legislature)</td></tr><tr><td><strong>UTGST</strong></td><td>Union Territories without legislature (Chandigarh, Lakshadweep, D&N Haveli, Daman & Diu, Andaman & Nicobar, Ladakh)</td></tr></tbody></table>`,
    faq: [
      { question: "Is SGST the same as the old state VAT?", answer: "SGST replaced state VAT, entry tax, entertainment tax, luxury tax, and several other state-level indirect taxes. While the concept of a state-collected consumption tax is similar, SGST is part of the unified GST framework with standardized rates and input credit mechanisms." },
      { question: "Can SGST credit be used across states?", answer: "No, SGST credit from one state cannot be used against SGST liability in another state. However, SGST credit can be used against IGST liability, which is useful for businesses that do both intra-state and inter-state sales." },
      { question: "Do all states have the same SGST rates?", answer: "Yes, GST rates are uniform across India. A product taxed at 18% will always be 9% CGST + 9% SGST/UTGST in every state. States cannot independently change the rate — only the GST Council can modify rates." }
    ]
  },
  "igst": {
    contentHTML: `<h3>What is IGST?</h3><p><strong>Integrated Goods and Services Tax (IGST)</strong> is levied on inter-state supply of goods and services (i.e., when seller and buyer are in different states) and on imports. The full IGST rate equals the sum of CGST + SGST rates. IGST is collected by the Central Government and then shared with the destination state.</p><h3>When IGST Applies</h3><table><thead><tr><th>Scenario</th><th>Tax Type</th><th>Example</th></tr></thead><tbody><tr><td>Seller in Maharashtra → Buyer in Gujarat</td><td>IGST</td><td>18% IGST</td></tr><tr><td>Import from USA to India</td><td>IGST + Customs</td><td>IGST on assessable value</td></tr><tr><td>E-commerce delivery across states</td><td>IGST</td><td>18% IGST</td></tr><tr><td>SEZ supply</td><td>IGST (zero-rated)</td><td>Refundable</td></tr></tbody></table><h3>IGST Settlement</h3><p>IGST collected by Central Government is later apportioned: the SGST-equivalent portion is transferred to the destination state. This ensures the consuming state gets its fair share of revenue.</p>`,
    faq: [
      { question: "Why is IGST needed if we have CGST and SGST?", answer: "IGST simplifies inter-state transactions. Without it, cross-state trade would require complex accounting between two states. IGST acts as a single tax on inter-state supply, and the central government handles the revenue sharing with the destination state afterward." },
      { question: "Can IGST credit be used against CGST and SGST?", answer: "Yes, IGST credit can be used against IGST, CGST, and SGST liabilities in that order of priority. This is the most flexible credit type. CGST credit can offset CGST or IGST. SGST credit can offset SGST or IGST." },
      { question: "Is IGST charged on all online purchases?", answer: "It depends on where the seller and buyer are located. If both are in the same state, CGST + SGST applies. If in different states, IGST applies. Most large e-commerce platforms display the correct tax type automatically based on shipping address." }
    ]
  },
  "input-tax-credit": {
    contentHTML: `<h3>What is Input Tax Credit?</h3><p><strong>Input Tax Credit (ITC)</strong> allows businesses to reduce the GST they owe (output tax) by claiming credit for the GST they have already paid on purchases (input tax). This prevents double taxation and ensures tax is levied only on the <strong>value addition</strong> at each stage.</p><h3>How ITC Works — Example</h3><table><thead><tr><th>Stage</th><th>Purchase (Input)</th><th>Sale (Output)</th><th>GST Paid</th><th>ITC Claimed</th><th>Net GST to Govt</th></tr></thead><tbody><tr><td>Raw Material Supplier</td><td>—</td><td>₹1,000</td><td>₹180</td><td>—</td><td>₹180</td></tr><tr><td>Manufacturer</td><td>₹1,000</td><td>₹2,000</td><td>₹360</td><td>₹180</td><td>₹180</td></tr><tr><td>Retailer</td><td>₹2,000</td><td>₹3,000</td><td>₹540</td><td>₹360</td><td>₹180</td></tr><tr><td><strong>Total</strong></td><td></td><td></td><td></td><td></td><td><strong>₹540</strong></td></tr></tbody></table><h3>Items Where ITC Is Blocked</h3><ul><li>Motor vehicles (except for transport/resale)</li><li>Food and beverages, outdoor catering</li><li>Personal consumption</li><li>Beauty treatment, health services</li><li>Works contract for construction of immovable property</li></ul>`,
    faq: [
      { question: "How do I claim Input Tax Credit?", answer: "To claim ITC: (1) you must have a valid GST tax invoice, (2) the supplier must have filed their GSTR-1, (3) you must have received the goods/services, (4) tax must actually be paid to the government by the supplier, and (5) the purchases must be used for business purposes." },
      { question: "Can I claim ITC on all business purchases?", answer: "No, ITC is blocked on certain items like motor vehicles, food/beverages, personal consumption, and construction of immovable property. ITC is available only for purchases used in furtherance of business and only from GST-registered suppliers." },
      { question: "What happens to unused ITC?", answer: "Unused ITC is carried forward to the next tax period. If you consistently accumulate excess ITC (due to higher rate on inputs than outputs, or exports), you can apply for a refund. ITC must be claimed within a specific time limit — before filing the return for September of the following financial year." }
    ]
  },
  "stcg": {
    contentHTML: `<h3>What is STCG?</h3><p><strong>Short-Term Capital Gains (STCG)</strong> is the profit earned from selling a capital asset held for a short duration. The holding period that qualifies as "short-term" varies by asset type.</p><h3>Short-Term Holding Periods</h3><table><thead><tr><th>Asset Type</th><th>Short-Term If Held For</th><th>STCG Tax Rate</th></tr></thead><tbody><tr><td><strong>Listed Equity Shares</strong></td><td>Less than 12 months</td><td>20% (flat)</td></tr><tr><td><strong>Equity Mutual Funds</strong></td><td>Less than 12 months</td><td>20% (flat)</td></tr><tr><td><strong>Debt Mutual Funds</strong></td><td>Less than 24 months</td><td>As per income tax slab</td></tr><tr><td><strong>Real Estate</strong></td><td>Less than 24 months</td><td>As per income tax slab</td></tr><tr><td><strong>Gold/Jewellery</strong></td><td>Less than 24 months</td><td>As per income tax slab</td></tr></tbody></table><h3>STCG vs. LTCG (Listed Equity)</h3><table><thead><tr><th>Feature</th><th>STCG</th><th>LTCG</th></tr></thead><tbody><tr><td>Holding period</td><td>< 12 months</td><td>≥ 12 months</td></tr><tr><td>Tax rate</td><td>20%</td><td>12.5% (above ₹1.25L exemption)</td></tr><tr><td>Exemption</td><td>None</td><td>₹1.25 lakh/year</td></tr></tbody></table>`,
    faq: [
      { question: "How is STCG on shares calculated?", answer: "STCG = Sale Price − Purchase Price − Brokerage/Charges. For listed equity shares and equity mutual funds held less than 12 months, STCG is taxed at a flat rate of 20% (plus cess). For other assets, STCG is added to your income and taxed at your slab rate." },
      { question: "Can I offset STCG against losses?", answer: "Yes, short-term capital losses can be set off against both STCG and LTCG. If losses are not fully utilized in the same year, they can be carried forward for up to 8 assessment years and set off against future capital gains." },
      { question: "Is STCG applicable on intraday trading?", answer: "No, intraday (same-day) trading profits are classified as speculative business income, not capital gains. They are taxed at your income tax slab rate. STCG applies only when you buy and sell on different days (delivery-based trading)." }
    ]
  },
  "professional-tax": {
    contentHTML: `<h3>What is Professional Tax?</h3><p><strong>Professional Tax</strong> is a state-level tax levied on salaried individuals and professionals earning income from their profession or employment. It is deducted by the employer from the salary and deposited with the state government. Not all states levy professional tax.</p><h3>Professional Tax Rates (Select States)</h3><table><thead><tr><th>State</th><th>Monthly Rate (Max)</th><th>Annual Max</th></tr></thead><tbody><tr><td><strong>Maharashtra</strong></td><td>₹200/month (₹300 in Feb)</td><td>₹2,500</td></tr><tr><td><strong>Karnataka</strong></td><td>₹200/month</td><td>₹2,400</td></tr><tr><td><strong>West Bengal</strong></td><td>₹150/month</td><td>₹2,500</td></tr><tr><td><strong>Telangana</strong></td><td>₹200/month</td><td>₹2,500</td></tr><tr><td><strong>Tamil Nadu</strong></td><td>₹208/month</td><td>₹2,500</td></tr><tr><td><strong>Delhi, UP, Rajasthan</strong></td><td>Not applicable</td><td>₹0</td></tr></tbody></table><h3>Tax Benefit</h3><p>Professional tax paid is <strong>fully deductible</strong> from gross salary when computing taxable income under both old and new tax regimes.</p>`,
    faq: [
      { question: "Is professional tax deductible from income tax?", answer: "Yes, professional tax paid during the year is fully deductible from your gross salary while computing taxable income. This benefit is available under both old and new tax regimes." },
      { question: "Do freelancers and self-employed professionals need to pay professional tax?", answer: "Yes, in states that levy professional tax, self-employed professionals (doctors, lawyers, CAs, architects, etc.) are also liable to register and pay professional tax if their income exceeds the threshold." },
      { question: "What is the maximum professional tax that can be charged?", answer: "As per Article 276 of the Constitution, the maximum professional tax that a state can levy is ₹2,500 per year. No state can charge more than this annual limit." }
    ]
  },
  "surcharge": {
    contentHTML: `<h3>What is Surcharge?</h3><p><strong>Surcharge</strong> is an additional tax levied on top of the income tax for high-income individuals and companies. It is a "tax on tax" — calculated as a percentage of the income tax payable, not on the income itself.</p><h3>Surcharge Rates for Individuals (FY 2024-25)</h3><table><thead><tr><th>Taxable Income</th><th>Surcharge Rate (Old Regime)</th><th>Surcharge Rate (New Regime)</th></tr></thead><tbody><tr><td>Up to ₹50 lakhs</td><td>Nil</td><td>Nil</td></tr><tr><td>₹50L – ₹1 crore</td><td>10%</td><td>10%</td></tr><tr><td>₹1 crore – ₹2 crore</td><td>15%</td><td>15%</td></tr><tr><td>₹2 crore – ₹5 crore</td><td>25%</td><td>25% (max)</td></tr><tr><td>Above ₹5 crore</td><td>37%</td><td>25% (capped)</td></tr></tbody></table><h3>Marginal Relief</h3><p>Marginal relief ensures that the surcharge does not result in you paying more tax than the additional income that pushed you into the surcharge bracket. The tax department automatically applies this relief during ITR processing.</p>`,
    faq: [
      { question: "How is surcharge calculated?", answer: "Surcharge is calculated as a percentage of income tax, not income. For example, if your income tax is ₹20,00,000 and the surcharge rate is 15%, the surcharge is ₹3,00,000. The total tax becomes ₹23,00,000 plus 4% health and education cess on this total." },
      { question: "Is surcharge applicable on capital gains?", answer: "Yes, surcharge applies on the total income tax including tax on capital gains. However, for listed equity LTCG and STCG, the maximum surcharge is capped at 15% under both old and new regimes." },
      { question: "What is the difference between surcharge and cess?", answer: "Surcharge is levied only on high-income individuals and increases with income. Cess (Health & Education Cess at 4%) is levied on ALL taxpayers regardless of income level. Both are calculated on the income tax amount, not on income directly." }
    ]
  }
};

let updated = 0;
data.forEach(term => {
  if (enrichments[term.slug]) {
    term.contentHTML = enrichments[term.slug].contentHTML;
    term.faq = enrichments[term.slug].faq;
    updated++;
  }
});

fs.writeFileSync('./data/glossary.json', JSON.stringify(data, null, 2));
console.log('Updated ' + updated + ' tax terms (batch 1)');
